AWSTemplateFormatVersion: '2010-09-09'
Description: A starter AWS Lambda function.
Outputs:
  ColorGeneratorArn:
    Description: Lambda Rule Arn
    Export:
      Name:
        Fn::Sub: ${AWS::StackName}-ColorGeneratorLambda
    Value:
      Fn::GetAtt:
      - ColorGeneratorLambda
      - Arn
Resources:
  ColorGeneratorLambda:
    Properties:
      CodeUri: s3://giallo-deployment/595a03076eff6e10165a378068cdaa9c
      Description: Lambda Color Generator
      Handler: index.handler
      MemorySize: 128
      Role:
        Fn::GetAtt:
        - ColorGeneratorRole
        - Arn
      Runtime: nodejs8.10
      Timeout: 5
    Type: AWS::Serverless::Function
  ColorGeneratorRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action:
          - sts:AssumeRole
          Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
        Version: '2012-10-17'
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/AmazonS3FullAccess
      Path: /
      Policies:
      - PolicyDocument:
          Statement:
          - Action:
            - logs:*
            Effect: Allow
            Resource: arn:aws:logs:*:*:*
          Version: '2012-10-17'
        PolicyName: logs
    Type: AWS::IAM::Role
Transform: AWS::Serverless-2016-10-31
