const region = 'eu-west-1';
const bucket_name = 'giallo-deployment';
const partition_name = 'images';
const sw = require('stopword')
const ntc = require('ntc');
const aws = require('aws-sdk');
const Harmonizer = require('color-harmony').Harmonizer;
const Jimp = require('jimp');
const async = require('async');

const harmonizer = new Harmonizer();
const s3Client = new aws.S3({region: region});

const names = [['000000', 'Nero', 'Black'],
['000080', 'Blu Marino', 'Navy Blue'],
['0000C8', 'Blu Scuro', 'Dark Blue'],
['0000FF', 'Blu', 'Blue'],
['000741', 'Blu Notte' 'Stratos'],
['001B1C', 'Blu Notte Scuro', 'Swamp', 'Palude'],
['002387', 'Blu Risoluzione', 'Resolution Blue'],
['002900', 'Abete intenso', 'Deep Fir'],
['002E20', 'Burnham', 'Burnham'],
['002FA7', 'Blu Klein', 'International Klein Blue'],
['003153', 'Blu Prussia', 'Prussian Blue'],
['003366', 'Blu Notte', 'Midnight Blue'],
['003399', 'Blu Elettrico', 'Smalt'],
['003532', 'Turchese Intenso', 'Deep Teal'],
['003E40', 'Cipro', 'Cyprus'],
['004620', 'Verde Kaitoke', 'Kaitoke Green'],
['0047AB', 'Cobalto', 'Cobalt'],
['004816', 'Verde Mare Intenso', 'Crusoe'],
['004950', 'Blu Sherpa', 'Sherpa Blue'],
['0056A7', 'Tentativo', 'Endeavour'],
['00581A', 'Camarone', 'Camarone'],
['0066CC', 'Blu Scienza', 'Science Blue'],
['0066FF', 'Blu Nastro', 'Blue Ribbon'],
['00755E', 'Foresta Pluviale Tropicale', 'Tropical Rain Forest'],
['0076A3', 'Ciano Chiaro', 'Allports'],
['007BA7', 'Ceruleo', 'Deep Cerulean'],
['007BB8', 'Blu Comando Stellare', 'Blu Comando Stellare'],
['007EC7', 'Azzurro Chiaro', 'Lochmara'],
['007FFF', 'Azzurro', 'Azure Radiance'],
['008000', 'Verde Ufficio'],
['008080', 'Verde Foglia di Tè', 'Teal'],
['0095B6', 'Blu Bondi', 'Bondi Blue'],
['009DC4', 'Blu Oceano Pacifico', 'Pacific Blue'],
['00A693', 'Verde Persiano', 'Persian Green'],
['00A86B', 'Giada', 'Jade'],
['00CC99', 'Verde Caraibi', 'Caribbean Green'],
['00CCCC', 'Uovo di Pettirosso', "Robin's Egg Blue"],
['00FF00', 'Verde', 'Green'],
['00FF7F', 'Verde Primavera', 'Spring Green'],
['00FFFF', 'Ciano', 'Cyan', 'Aqua', 'Acqua'],
['010D1A', 'Blu Carbone', 'Blue Charcoal'],
['011635', 'Blu di Mezzanotte', 'Midnight'],
['011D13', 'Agrifoglio', 'Holly'],
['012731', 'Ciano Scuro', 'Daintree'],
['01361C', 'Verde Primavera Molto Scuro', 'Cardin Green'],
['01371A', 'Verde Contea', 'County Green'],
['013E62', 'Blu Astronauta', 'Astronaut Blue'],
['013F6A', 'Azzurro Scuro', 'Regal Blue'],
['014B43', 'Acqua Intenso', 'Aqua Deep'],
['015E85', 'Oriente', 'Orient'],
['016162', 'Blu Pietra', 'Blue Stone'],
['016D39', 'Verde Divertimento', 'Fun Green'],
['01796F', 'Verde Pino', 'Pine Green'],
['017987', 'Blu Laguna', 'Blue Lagoon'],
['01826B', 'Mare Intenso', 'Deep Sea'],
['01A368', 'Verde Primavera Chiaro', 'Green Haze'],
['022D15', 'Agrifoglio Inglese', 'English Holly'],
['02402C', 'Verde Sherwood', 'Sherwood Green'],
['02478E', 'Blu Congresso', 'Congress Blue'],
['024E46', 'Mare di Sera', 'Evening Sea'],
['026395', 'Blu Bahama', 'Bahama Blue'],
['02866F', 'Osservatorio', 'Observatory'],
['02A4D3', 'Ceruleo', 'Cerulean'],
['03163C', 'Canguro', 'Tangaroa'],
['032B52', 'Verde Vogue', 'Green Vogue'],
['036A6E', 'Moschea', 'Mosque'],
['041004', 'Muschio di Mezzanotte', 'Midnight Moss'],
['041322', 'Perla Nera', 'Black Pearl'],
['042E4C', 'Blu Balena', 'Blue Whale'],
['044022', 'Zucchine', 'Zuccini'],
['044259', 'Blu Turchese', 'Teal Blue'],
['050402', 'Carbone', 'Carbone'],
['051040', 'Baia Profonda', 'Deep Cove'],
['051657', 'Blu del Golfo', 'Gulf Blue'],
['055989', 'Blu Veneziano', 'Venice Blue'],
['056F57', 'Alveo', 'Watercourse'],
['062A78', 'Blu Catalina', 'Catalina Blue'],
['063537', 'Tevere', 'Tiber'],
['069B81', 'Gossamer', 'Gossamer'],
['06A189', 'Niagara', 'Niagara'],
['073A50', 'Tarawera', 'Tarawera'],
['080110', 'Giaguaro', 'Jaguar'],
['081910', 'Fagiolo Nero', 'Black Bean'],
['082567', 'Zaffiro Intenso', 'Deep Sapphire'],
['08457E', 'Ceruleo Scuro', 'Ceruleo Scuro'],
['088370', 'Verde Elfo', 'Elf Green'],
['08E8DE', 'Turchese Chiaro', 'Bright Turquoise'],
['092256', 'Downriver', 'Downriver'],
['09230F', 'Verde Palma', 'Palm Green'],
['09255D', 'Madison', 'Madison'],
['093624', 'Verde bottiglia', 'Bottle Green'],
['095859', 'Verde Mare Intenso', 'Deep Sea Green'],
['097F4B', 'Salmo', 'Salem'],
['0A001C', 'Nero Russo', 'Black Russian'],
['0A480D', 'Felce Scura', 'Dark Fern'],
['0A6906', 'Alloro Giapponese', 'Japanese Laurel'],
['0A6F75', 'Atollo', 'Atoll'],
['0B0B0B', 'Grigio Merluzzo', 'Cod Gray'],
['0B0F08', 'Padule', 'Marshland'],
['0B1107', 'Verde Gordon', 'Gordons Green'],
['0B1304', 'Foresta Nera', 'Black Forest'],
['0B6207', 'San Felice', 'San Felix'],
['0BDA51', 'Malachite', 'Malachite'],
['0C0B1D', 'Ebano', 'Ebony'],
['0C0D0F', 'Fumo', 'Woodsmoke'],
['0C1911', 'Verde da Corsa', 'Racing Green'],
['0C7A79', 'Verde Surfie', 'Surfie Green'],
['0C8990', 'Blu Freddo', 'Blue Chill'],
['0D0332', 'Roccia Nera', 'Black Rock'],
['0D1117', 'Bunker', 'Bunker'],
['0D1C19', 'Azteco', 'Aztec'],
['0D2E1C', 'Cespuglio', 'Bush'],
['0E0E18', 'Brace', 'Cinder'],
['0E2A30', 'Lucciola', 'Firefly'],
['0F2D9E', 'Baia di Corea', 'Torea Bay'],
['0F52BA', 'Zaffiro', 'Zaffiro'],
['10121D', 'Vulcano', 'Vulcan'],
['101405', 'Verde Waterloo', 'Green Waterloo'],
['105852', 'Eden', 'Eden'],
['110C6C', 'Arapawa', 'Arapawa'],
['116062', 'Turchese Scuro', 'Turchese Scuro'],
['120A8F', 'Blu Oltremare', 'Ultramarine'],
['123447', 'Elefante', 'Elephant'],
['126B40', 'Gioiello', 'Jewel'],
['130000', 'Diesel', 'Diesel'],
['130A06', 'Asfalto', 'Asphalt'],
['13264D', 'Blu Zodiaco', 'Blue Zodiac'],
['134F19', 'Prezzemolo', 'Parsley'],
['140600', 'Nero', 'Nero'],
['1450AA', 'Blu Tory', 'Tory Blue'],
['151F4C', 'Pavese', 'Bunting'],
['1560BD', 'Denim', 'Denim'],
['15736B', 'Genova', 'Genoa'],
['161928', 'Miraggio', 'Mirage'],
['161D10', 'Verde Hunter', 'Hunter Green'],
['162A40', 'Pietra Grande', 'Big Stone'],
['163222', 'Celtico', 'Celtic'],
['16322C', 'Verde Legname', 'Timber Green'],
['163531', 'Verde Timpano', 'Gable Green'],
['171F04', 'Pino', 'Pine Tree'],
['175579', 'Blu Chathams', 'Chathams Blue'],
['177245', 'Verde Primavera Scuro', 'Verde Primavera Scuro'],
['182D09', 'Verde Foresta Profonda', 'Deep Forest Green'],
['18587A', 'Blumina', 'Blumine'],
['19330E', 'Foglia di Palma', 'Palm Leaf'],
['193751', 'Blu Nilo', 'Nile Blue'],
['1959A8', 'Blu Divertimento', 'Fun Blue'],
['1A1A68', 'Punto Fortunato', 'Lucky Point'],
['1AB385', 'Prato di Montagna', 'Mountain Meadow'],
['1B0245', 'Tolopea', 'Tolopea'],
['1B1035', 'Haiti', 'Haiti'],
['1B127B', 'Koamaru Intenso', 'Deep Koamaru'],
['1B1404', 'Acadia', 'Acadia'],
['1B2F11', 'Alga Marina', 'Seaweed'],
['1B3162', 'Biscaglia', 'Biscay'],
['1B659D', 'Matisse', 'Matisse'],
['1C1208', 'Corvo', 'Crowshead'],
['1C1E13', 'Verde Rangoon', 'Rangoon Green'],
['1C39BB', 'Blu di Persia', 'Persian Blue'],
['1C402E', 'Everglade', 'Everglade'],
['1C7C7D', 'Azzurro Scienza', 'Elm'],
['1D6142', 'Verde Pisello', 'Green Pea'],
['1E0F04', 'Creolo', 'Creole'],
['1E1609', 'Karaka', 'Orologio'],
['1E1708', 'El Paso', 'El Paso'],
['1E385B', 'Violoncello', 'Cello'],
['1E433C', 'Verde Papa', 'Te Papa Green'],
['1E90FF', 'Blu Dodger', 'Dodger Blue'],
['1E9AB0', 'Blu Orientale', 'Eastern Blue'],
['1F120F', 'Pilota di Notte', 'Night Rider'],
['1FC2C2', 'Java', 'Java'],
['20208D', 'Viola Jackson', 'Jacksons Purple'],
['202E54', 'Scoppio di Nuvola', 'Cloud Burst'],
['204852', 'Blu Dianne', 'Blue Dianne'],
['211A0E', 'Eternità', 'Eternity'],
['220878', 'Blu Intenso', 'Deep Blue'],
['228B22', 'Verde Foresta', 'Forest Green'],
['233418', 'Mallardo', 'Mallard'],
['240A40', 'Viola', 'Violet'],
['240C02', 'Kilimanjaro', 'Kilamanjaro'],
['242A1D', 'Log Cabin', 'Log Cabin'],
['242E16', 'Nero Oliva', 'Black Olive'],
['24500F', 'Casa Verde', 'Green House'],
['251607', 'Grafite', 'Graphite'],
['251706', 'Nero Cannone', 'Cannon Black'],
['251F4F', 'Port Gorè', 'Port Gore'],
['25272C', 'Squalo', 'Shark'],
['25311C', 'Verde Kelp', 'Green Kelp'],
['2596D1', 'Blu Curioso', 'Curious Blue'],
['260368', 'Paua', 'Paua'],
['26056A', 'Parigi', 'Paris M'],
['261105', 'Corteccia', 'Wood Bark'],
['261414', 'Gondola', 'Gondola'],
['262335', 'Grigio Acciaio', 'Steel Gray'],
['26283B', 'Ebano Argilla', 'Ebony Clay'],
['273A81', 'Bay of Many', 'Bay of Many'],
['27504B', 'Piantagione', 'Plantation'],
['278A5B', 'Eucalipto', 'Eucalyptus'],
['281E15', 'Olio', 'Oil'],
['283A77', 'Astronauta', 'Astronaut'],
['286ACD', 'Marinaio', 'Mariner'],
['290C5E', 'Violent Violet', 'Viola Violenta'],
['292130', 'Bastiglia', 'Bastille'],
['292319', 'Zeus', 'Zeus'],
['292937', 'Charade', 'Sciarada'],
['293133', 'Antracite', 'Antracite'],
['297B9A', 'Jelly Bean', 'Fagiolo di gelatina'],
['29AB87', 'Verde Giungla', 'Jungle Green'],
['2A0359', 'Cherry Pie', 'Torta di ciliegie'],
['2A140E', 'Chicco di Caffe', 'Coffee Bean'],
['2A2630', 'Mare Baltico', 'Baltic Sea'],
['2A380B', 'Verde Tartaruga', 'Turtle Green'],
['2A52BE', 'Blu Ceruleo', 'Cerulean Blue'],
['2B0202', 'Nero di seppia', 'Sepia Black'],
['2B194F', 'Valhalla', 'Valhalla'],
['2B3228', 'Heavy Metal', 'Metallo Pesante'],
['2C0E8C', 'Blu Gemma', 'Blue Gem'],
['2C1632', 'Revolver', 'rivoltella'],
['2C2133', 'Cedro Bianco', 'Bleached Cedar'],
['2C8C84', 'Lochinvar', 'Lochinvar'],
['2D2510', 'Mikado', 'Imperatore'],
['2D383A', 'Spazio', 'Outer Space'],
['2D569B', 'St. Tropez', 'St Tropaz'],
['2E0329', 'Jacaranda', 'Jacaranda'],
['2E1905', 'Jacko Bean', 'Fagiolo Jacko'],
['2E3222', 'Rangitoto', 'Rangitoto'],
['2E3F62', 'Rinoceronte', 'Rhino'],
['2E8B57', 'Verde Marino', 'Sea Green'],
['2EBFD4', 'Scooter', 'Scooter'],
['2F270E', 'Cipolla', 'Onion'],
['2F2F2F', 'Grigio 80%', 'Grigio 80%'],
['2F3CB3', 'Governor Bay', 'Baia del Governatore'],
['2F4F4F', 'Grigio Ardesia Scuro', 'Grigio Ardesia Scuro'],
['2F519E', 'Zaffiro', 'Sapphire'],
['2F5A57', 'Spettri', 'Spectra'],
['2F6168', 'Casal', 'Paio'],
['300529', 'Melanzana', 'Melanzane'],
['301F1E', 'Marrone Cacao', 'Cocoa Brown'],
['302A0F', 'Lucciola', 'Woodrush'],
['304B6A', 'San Juan', 'San Juan'],
['30D5C8', 'Turchese', 'Turquoise'],
['310062', 'Indaco Scuro', 'Indaco Scuro'],
['311C17', 'Eclisse', 'Eclipse'],
['314459', 'Pickled Bluewood', 'Legni Azzurri Decapati'],
['315BA1', 'Azzurro', 'Azure'],
['31728D', 'Calipso', 'Calypso'],
['317D82', 'Paradiso', 'Paradiso'],
['32127A', 'Indaco Persiano', 'Persian Indigo'],
['32293A', 'Ribes Nero', 'Blackcurrant'],
['323232', 'Miniera', 'Mine Shaft'],
['325D52', 'Stromboli', 'Stromboli'],
['327C14', 'Bilbao', 'Bilbao'],
['327DA0', 'Astrale', 'Astral'],
['32C6A6', 'Turchese Perla Mistica', 'Turchese Perla Mistica'],
['33036B', 'Christalle', 'Christalle'],
['33292F', 'Thunder', 'Tuono'],
['33CC99', 'Trifoglio', 'Shamrock'],
['341515', 'Tamarindo', 'Tamarind'],
['343A90', 'Blu notte', 'Blu notte'],
['350036', 'Mardi Gras', 'Martedì grasso'],
['350E42', 'Valentino', 'Valentino'],
['350E57', 'Pugnale', 'Jagger'],
['353542', 'Tonno', 'Tuna'],
['354E8C', 'Chambray', 'Chambray'],
['363050', 'Martinique', 'Martinica'],
['363534', 'Tuatara', 'Tuatara'],
['363C0D', 'Waiouru', 'Waiouru'],
['36747D', 'Ming', 'Ming'],
['368716', 'La Palma di Majorca', 'La Palma'],
['370202', 'Cioccolato', 'Chocolate'],
['371D09', 'Clinker', 'Clinker'],
['37290E', 'Marrone Tumbleweed', 'Brown Tumbleweed'],
['373021', 'Betulla', 'Birch'],
['377475', 'Oracolo', 'Oracle'],
['380474', 'Blu Diamante', 'Blue Diamond'],
['381A51', 'Uva', 'Grape'],
['383533', 'Duna', 'Dune'],
['384555', 'Blu Oxford', 'Oxford Blue'],
['384910', 'Trifoglio', 'Clover'],
['394851', 'Rosso Abete', 'Limed Spruce'],
['396413', 'Dell', 'Dell'],
['3A0020', 'Toledo', 'Toledo'],
['3A2010', 'Sambuca', 'Sambuca'],
['3A2A6A', 'Jakarta', 'Jacarta'],
['3A686C', 'Guglielmo', 'William'],
['3A6A47', 'Cillarino', 'Killarney'],
['3AB09E', 'Keppel', 'Keppel'],
['3B000B', 'Tentatrice', 'Temptress'],
['3B0910', 'Melanzana', 'Aubergine'],
['3B1F1F', 'Jon', 'Jon'],
['3B2820', "Casa sull'albero", 'Treehouse'],
['3B7A57', 'Amazzone', 'Amazon'],
['3B91B4', 'Blu Boston', 'Boston Blue'],
['3C0878', 'Windsor', 'Windsor'],
['3C1206', 'Ribelle', 'Rebel'],
['3C1F76', 'Meteorite', 'Meteorite'],
['3C2005', 'Ebano Scuro', 'Dark Ebony'],
['3C3910', 'Camuffare', 'Camouflage'],
['3C4151', 'Grigio Brillante', 'Bright Gray'],
['3C4443', 'Capo Cod', 'Cape Cod'],
['3C493A', 'Verde Lunare', 'Lunar Green'],
['3CB371', 'Verde Marino Medio', 'Verde marino medio'],
['3D0C02', 'Fagiolo', 'Bean  '],
['3D2B1F', 'Bistro', 'chiaro'],
['3D7D52', 'Goblin', 'Goblin'],
['3E0480', 'Martin Pescatore', 'Kingfisher Daisy', 'Martin Pescatore Daisy'],
['3E1C14', 'Cedro', 'Cedar'],
['3E2B23', 'Noce Inglese', 'English Walnut'],
['3E2C1C', 'Nero Marlin', 'Black Marlin'],
['3E3A44', 'Grigio Nave', 'Ship Gray'],
['3EABBF', 'Peloso', 'Pelorous'],
['3F2109', 'Bronzo', 'Bronze'],
['3F2500', 'Cola', 'Cola'],
['3F3002', 'Madras', 'Madras'],
['3F307F', 'Minsk', 'Minsk'],
['3F4C3A', 'Cavolo Pont', 'Cabbage Pont'],
['3F583B', 'Tom Thumb', 'Pollice del Pollice'],
['3F5D53', 'Verde Minerale', 'Mineral Green'],
['3FC1AA', 'Porto Rico', 'Puerto Rico'],
['3FFF00', 'Arlecchino', 'Harlequin'],
['401801', 'Marrone Baccello', 'Brown Pod'],
['40291D', 'Sughero', 'Cork'],
['403B38', 'Masala', 'Masala'],
['403D19', 'Verde Prugna', 'Thatch Green'],
['404040', 'Grigio 75%', 'Grigio 75%'],
['405169', 'Fiordo', 'Fiord'],
['40826D', 'Verde Veronese', 'viridian'],
['40A860', 'Verde Chateau', 'Chateau Green'],
['410012', 'Rubino', 'Rubino'],
['410056', 'Prugna Matura', 'Ripe Plum'],
['411F10', 'Paco', 'Paco'],
['412010', 'Rovere Intenso', 'Deep Oak'],
['413C37', 'Merlino', 'Merlin'],
['414257', 'Polvere da Sparo', 'Gun Powder'],
['414C7D', 'Baia Est', 'East Bay'],
['4169E1', 'Blu reale', 'Blu reale'],
['41AA78', 'Verde Oceano', 'Ocean Green'],
['420303', 'Burnt Maroon', 'Maroon Bruciato'],
['423921', 'Marrone Lisbona', 'Lisbon Brown'],
['427977', 'Fade Jade', 'Faded Jade'],
['431560', 'Gomma Scarlatta', 'Scarlet Gum'],
['433120', 'Iroko', 'Iroko'],
['433E37', 'Armadillo', 'Armadillo'],
['434C59', 'Grigio Alveo', 'River Bed'],
['436A0D', 'Verde Foglia', 'Green Leaf'],
['44012D', 'Barossa', 'Barossa'],
['441D00', 'Marrone Marocco', 'Morocco Brown'],
['444954', 'Mako', 'Mako'],
['454936', 'Kelp', 'Fuco'],
['456CAC', 'San Marino', 'San Marino'],
['45B1E8', 'Blu Pittografo', 'Picton Blue'],
['460B41', 'Loulou', 'Spitz'],
['462425', 'Marrone Cratere ', 'Crater Brown'],
['465945', 'Grigio Asparago', 'Asparagi grigi'],
['4682B4', 'Blu Acciaio', 'Blu acciaio'],
['480404', 'Rosso rustico', 'Rustic Red'],
['480607', 'Rosa bulgara', 'Bulgarian Rose'],
['480656', 'Chiaroveggente', 'Clairvoyant'],
['481C1C', 'Fava di cacao', 'Cocoa Bean'],
['483131', 'Marrone Legno', 'Woody Brown'],
['483C32', 'taupe', 'Taupe'],
['49170C', 'Furgone Cleef', 'Van Cleef'],
['492615', 'Derby marrone', 'Brown Derby'],
['49371B', 'Bronzo metallico', 'Metallic Bronze'],
['495400', 'Verde Verdun', 'Verdun Green'],
['496679', 'Bayoux blu', 'Blue Bayoux'],
['497183', 'Bismarck', 'Bismark'],
['4A2A04', 'felce', 'Bracken'],
['4A3004', 'Bronzo intenso', 'Deep Bronze'],
['4A3C30', 'Mondo', 'Mondo'],
['4A4244', 'tosa', 'Tundora'],
['4A444B', 'Ghiaia', 'Gravel'],
['4A4E5A', 'Trota', 'Trout'],
['4B0082', 'Indaco', 'Pigmento Indaco'],
['4B5D52', 'Nandoro', 'Nandor'],
['4C3024', 'Sella', 'Saddle'],
['4C4F56', 'Abbazia', 'Abbey'],
['4D0135', 'Mora', 'Blackberry'],
['4D0A18', 'Risparmio cabina', 'Cab Sav'],
['4D1E01', 'Tan indiano', 'Indian Tan'],
['4D282D', 'Cowboy', 'Cowboy'],
['4D282E', 'Marrone Livido', 'Livid Brown'],
['4D3833', 'Roccia', 'Rock'],
['4D3D14', 'pacchetti', 'Punga'],
['4D400F', 'Bronzetone', 'Bronzetone'],
['4D5328', 'bosco', 'Woodland'],
['4E0606', 'Mogano', 'Mahogany'],
['4E2A5A', 'Bossanova', 'Bossanova'],
['4E3B41', 'Cervino', 'Matterhorn'],
['4E420C', 'Oliva di Bronzo', 'Bronze Olive'],
['4E4562', 'Vin brulè', 'Mulled Wine'],
['4E6649', 'Axolotl', 'Axolotl'],
['4E7F9E', 'Cuneo', 'Wedgewood'],
['4EABD1', 'Shakespeare', 'Shakespeare'],
['4F1C70', 'Miele di fiori', 'Honey Flower'],
['4F2398', 'Margherita Cespuglio', 'Daisy Bush'],
['4F4F4F', 'Grigio 70%', 'Grigio 70%'],
['4F69C6', 'Indaco', 'Indigo'],
['4F7942', 'Verde Felce', 'Fern Green'],
['4F9D5D', 'Macedonia', 'Fruit Salad'],
['4FA83D', 'Mela', 'Apple'],
['500000', 'Rosso sangue', 'Rosso sangue'],
['504351', 'Mortaio', 'Mortar'],
['507096', 'Blu Kashmir', 'Kashmir Blue'],
['507672', 'Scuro tagliato', 'Cutty Sark'],
['50C878', 'Verde smeraldo', 'Smeraldo'],
['514649', 'imperatore', 'Emperor'],
['516E3D', 'Chalet Verde', 'Chalet Green'],
['517C66', 'come', 'Como'],
['51808F', 'Blu Smalto', 'Smalt Blue'],
['52001F', 'Castro', 'Castro'],
['520C17', 'Roverella', 'Maroon Oak'],
['523C94', 'gigas', 'Gigas'],
['531B00', 'Terra di Siena bruciata', 'Terra di Siena bruciata'],
['533455', 'vudù', 'Voodoo'],
['534491', 'Vittoria', 'Victoria'],
['53824B', 'Verde Hippie', 'Hippie Green'],
['541012', 'Brughiera', 'Heath'],
['544333', 'Giudice Gray', 'Judge Gray'],
['54534D', 'Fuscous Grey', 'Fuscous Gray'],
['549019', 'Loca Vida', 'Vida Loca'],
['55280C', 'Cioccolato', 'Cioccolato'],
['555B10', 'Saratoga', 'Saratoga'],
['556B2F', 'Verde oliva scuro', 'Verde oliva scuro'],
['556D56', 'Finlandia', 'Finlandia'],
['5590D9', 'Blu Havelock', 'Havelock Blue'],
['560319', 'Scarlatto scuro', 'Scarlatto scuro'],
['56B4BE', 'Fontana blu', 'Fountain Blue'],
['578363', 'Foglie di primavera', 'Spring Leaves'],
['583401', 'Sella marrone', 'Saddle Brown'],
['585562', 'Flusso Scarpa', 'Scarpa Flow'],
['587156', 'Cactus', 'Cactus'],
['589AAF', 'Blu Hippie', 'Hippie Blue'],
['591D35', 'Bacca di vino', 'Wine Berry'],
['592804', 'Rovolio Marrone', 'Brown Bramble'],
['593737', 'Congo Marrone', 'Congo Brown'],
['594433', 'Millbrook', 'Millbrook'],
['5A6E9C', 'Waikawa Grey', 'Waikawa Gray'],
['5A87A0', 'Orizzonte', 'Horizon'],
['5B3013', 'Jambalaya', 'Jambalaya'],
['5C0120', 'bordò', 'Bordeaux'],
['5C0536', 'Legno di gelso', 'Mulberry Wood'],
['5C2E01', 'Carnevale', 'Carnaby Tan'],
['5C5D75', 'Cometa', 'Comet'],
['5D1E0F', 'sequoia', 'Redwood'],
['5D4C51', 'Don Giovanni', 'Don Juan'],
['5D5C58', 'Chicago', 'Chicago'],
['5D5E37', 'Verderame', 'Verdigris'],
['5D7747', 'Dingley', 'Dingley'],
['5D8AA8', 'voli', 'Avio'],
['5DA19F', 'Interruttore Bay', 'Breaker Bay'],
['5E483E', 'accettazione', 'Kabul'],
['5E5D3B', 'Cicuta', 'Hemlock'],
['5E86C1', 'Denim chiaro', 'Denim chiaro'],
['5F3D26', 'Caffé irlandese', 'Irish Coffee'],
['5F5F5F', 'Grigio 60%', 'Grigio 60%'],
['5F5F6E', 'Grigio medio', 'Mid Gray'],
['5F6672', 'Shuttle Grey', 'Shuttle Gray'],
['5F9EA0', 'Cadetto blu', 'Blu cadetto'],
['5FA777', 'Aqua foresta', 'Aqua Forest'],
['5FB3AC', 'Vento', 'Tradewind'],
['604913', 'Collo di cavalli', 'Horses Neck'],
['605B73', 'fumoso', 'Smoky'],
['606E68', 'Velluto a coste', 'Corduroy'],
['6093D1', 'Danubio', 'Danube'],
['612718', 'Espresso', 'Espresso'],
['614051', 'Melanzana', 'Eggplant'],
['615D30', 'Costa del Sol', 'Costa Del Sol'],
['61845F', 'Verde radura', 'Glade Green'],
['622F30', 'pirata', 'Buccaneer'],
['623F2D', 'Quinzacia', 'Quincy'],
['624E9A', 'Farfalla Cespuglio', 'Butterfly Bush'],
['625119', 'costa ovest', 'West Coast'],
['626649', 'fringuello', 'Finch'],
['635147', "Terra d'ombra", "Terra d'ombra"],
['639A8F', 'Patina', 'Patina'],
['63B76C', 'Felce', 'Fern'],
['6456B7', 'Blu viola', 'Blue Violet'],
['646077', 'Delfino', 'Dolphin'],
['646463', 'Polvere di tempesta', 'Storm Dust'],
['646A54', 'Siam', 'Siam'],
['646B63', 'Grigio topo', 'Grigio topo'],
['646E75', 'Nevada', 'Nevada'],
['6495ED', 'Fiore di granturco', 'Blu fiordaliso'],
['64CCDB', 'vichingo', 'Viking'],
['65000B', 'Palissandro', 'Rosewood'],
['651A14', 'Legno di ciliegio', 'Cherrywood'],
['652DC1', 'Cuore viola', 'Purple Heart'],
['654321', 'Marrone scuro', 'Marrone scuro'],
['657220', 'Felce Frond', 'Fern Frond'],
['65745D', 'Saliceto', 'Willow Grove'],
['65869F', 'ritorno', 'Hoki'],
['660045', 'Pompadour', 'Pompadour'],
['660066', 'Prugna', 'Prugna'],
['660099', 'Viola', 'Purple'],
['66023C', 'Porpora Tiriano', 'Tyrian Purple'],
['661010', 'Abbronzatura scura', 'Dark Tan'],
['66B58F', "Albero d'argento", 'Silver Tree'],
['66FF00', 'Verde chiaro', 'Verde acceso'],
['66FF66', "Screamin 'Green", "Screamin' Green"],
['67032D', 'Rosa nera', 'Black Rose'],
['675FA6', 'Scampi', 'Scampi'],
['676662', 'Ironside Grey', 'Ironside Gray'],
['678975', 'Verde Virida', 'Viridian Green'],
['67A712', 'Domini', 'Christi'],
['683600', 'Finitura legno noce moscata', 'Nutmeg Wood Finish'],
['685558', 'Zambesi', 'Zambezi'],
['685E6E', 'Scatola di sale', 'Salt Box'],
['692545', 'Porto Tawny', 'Tawny Port'],
['692D54', 'trovare', 'Finn'],
['695F62', 'Scorpione', 'Scorpion'],
['697E9A', 'linciare', 'Lynch'],
['6A442E', 'Spezia', 'Spice'],
['6A5D1B', 'Himalaya', 'Himalaya'],
['6A6051', 'Semi di soia', 'Soya Bean'],
['6B2A14', 'Heath peloso', 'Hairy Heath'],
['6B3FA0', 'Porpora Reale', 'Royal Purple'],
['6B4E31', 'Fascino cerbiatto', 'Shingle Fawn'],
['6B5755', "d'oro", 'Dorado'],
['6B8BA2', 'Bermuda Grey', 'Bermuda Gray'],
['6B8E23', 'Verde olivastro', 'Oliva Drab'],
['6C3082', 'Eminenza', 'Eminence'],
['6CDAE7', 'Blu turchese', 'Turquoise Blue'],
['6D0101', 'Stella solitaria', 'Lonestar'],
['6D5E54', 'Pigna', 'Pine Cone'],
['6D6C6C', 'Grigio Colomba', 'Dove Gray'],
['6D9292', 'Ginepro', 'Juniper'],
['6D92A1', 'Gotico', 'Gothic'],
['6E0902', 'Ossido rosso', 'Red Oxide'],
['6E1D14', 'Moccaccino', 'Moccaccino'],
['6E4826', 'Fagiolo sottaceto', 'Pickled Bean'],
['6E4B26', 'Dallas', 'Dallas'],
['6E6D57', 'Kokoda', 'Kokoda'],
['6E7783', 'Cielo Pallido', 'Pale Sky'],
['6F00FF', 'Indaco elettrico', 'Indaco elettrico'],
['6F440C', 'Caffè Royale', 'Cafe Royale'],
['6F6A61', 'pietra focaia', 'Flint'],
['6F8E63', 'montanaro', 'Highland'],
['6F9D02', 'limeade', 'Limeade'],
['6FD0C5', 'Lanuginoso', 'Downy'],
['701C1C', 'Prugna persiana', 'Persian Plum'],
['704214', 'Seppia', 'nero di seppia'],
['704A07', 'Bronzo antico', 'Antique Bronze'],
['704F50', 'Ferra', 'Ferra'],
['706555', 'caffè', 'Coffee'],
['708090', 'Ardesia', 'Ardesia grigia'],
['711A00', 'Finitura in legno di cedro', 'Cedar Wood Finish'],
['71291D', 'Rame metallico', 'Metallic Copper'],
['714693', 'Affare', 'Affair'],
['714AB2', 'Studio', 'Studio'],
['715D47', 'Tabacco marrone', 'Tobacco Brown'],
['716338', 'Metallo giallo', 'Yellow Metal'],
['716B56', 'Torba', 'Peat'],
['716E10', 'Olivetone', 'Olivetone'],
['717486', 'Storm Grey', 'Storm Gray'],
['718080', 'Scirocco', 'Sirocco'],
['71D9E2', 'Blu acquamarina', 'Aquamarine Blue'],
['72010F', 'Rosso veneziano', 'Venetian Red'],
['724A2F', 'Vecchio rame', 'Old Copper'],
['726D4E', 'Vai Ben', 'Go Ben'],
['727B89', 'Corvo', 'Raven'],
['731E8F', 'seduta', 'Seance'],
['734A12', 'Umber crudo', 'Raw Umber'],
['736C9F', 'Kimberly', 'Kimberly'],
['736D58', 'Coccodrillo', 'Crocodile'],
['737829', 'Creta', 'Crete'],
['738678', 'xanadu', 'Xanadu'],
['74640D', 'Mostarda piccante', 'Spicy Mustard'],
['747D63', 'Cenere friabile', 'Limed Ash'],
['747D83', 'Pietra Rotolata', 'Rolling Stone'],
['748881', 'Fumo blu', 'Blue Smoke'],
['749378', 'Alloro', 'Laurel'],
['74C365', 'Mantide', 'Mantis'],
['754909', 'Testa di Moro', 'Testa di moro'],
['755A57', 'Russettarsi', 'Russett'],
['7563A8', 'Diluvio', 'Deluge'],
['75663F', 'Bronzo antico', 'Bronzo antico'],
['76395D', 'Cosmico', 'Cosmic'],
['7666C6', 'Marguerite blu', 'Blue Marguerite'],
['76BD17', 'calce', 'Lima'],
['76D7EA', 'Cielo blu', 'Sky Blue'],
['770F05', 'Borgogna scura', 'Dark Burgundy'],
['771F1F', 'Corona di spine', 'Crown of Thorns'],
['773F1A', 'Noce', 'Walnut'],
['776F61', 'Pablo', 'Pablo'],
['778120', 'Pacifico', 'Pacifika'],
['778899', 'Grigio ardesia chiaro', 'Grigio ardesia chiaro'],
['779E86', 'Oxley', 'Oxley'],
['77DD77', 'Verde pastello', 'Verde pastello'],
['780109', 'Acero giapponese', 'Japanese Maple'],
['782D19', 'moca', 'Mocha'],
['782F16', 'arachide', 'Peanut'],
['78866B', 'Verde mimetico', 'Camouflage Green'],
['788A25', 'Wasabi', 'Wasabi'],
['788BBA', 'Nave insenatura', 'Ship Cove'],
['78A39C', 'Ninfa marina', 'Sea Nymph'],
['79443B', 'Tronco', 'Tronco'],
['795D4C', 'Caffè romano', 'Roman Coffee'],
['796878', 'Vecchia lavanda', 'Old Lavender'],
['796989', 'camere', 'Rum'],
['796A78', 'Fedora', 'Fedora'],
['796D62', 'Arenaria', 'Sandstone'],
['79DEEC', 'Spray', 'Spray'],
['7A013A', 'Sirena', 'Siren'],
['7A58C1', 'Blu fucsia', 'Fuchsia Blue'],
['7A7A7A', 'Masso', 'Boulder'],
['7A89B8', 'Yonder blu selvatico', 'Wild Blue Yonder'],
['7AC488', 'York', 'De York'],
['7B1B02', 'Granata', 'Granata'],
['7B3801', 'Faggio rosso', 'Red Beech'],
['7B3F00', 'Cannella', 'Cinnamon'],
['7B6608', 'Oro Yukon', 'Yukon Gold'],
['7B7874', 'modo', 'Tapa'],
['7B7C94', 'Waterloo', 'Waterloo '],
['7B8265', 'Fumo di lino', 'Flax Smoke'],
['7B9F80', 'Amuleto', 'Amulet'],
['7BA05B', 'Asparago', 'Asparagus'],
['7C1C05', 'Rame keniota', 'Kenyan Copper'],
['7C7631', 'Pesto', 'Pesto'],
['7C778A', 'Topazio', 'Topaz'],
['7C7B7A', 'Concordia', 'Concord'],
['7C7B82', 'Jumbo', 'Jumbo'],
['7C881A', 'Verde alla moda', 'Trendy Green'],
['7CA1A6', 'Gumbo', 'Gumbo'],
['7CB0A1', 'Acapulco', 'Acapulco'],
['7CB7BB', 'Nettuno', 'Neptune'],
['7D2C14', 'persone', 'Pueblo'],
['7DA98D', "Foglia d'alloro", 'Bay Leaf'],
['7DC8F7', 'Malibù', 'Malibu'],
['7DD8C6', 'Bermuda', 'Bermuda'],
['7E3A15', 'Rame Canyon', 'Copper Canyon'],
['7F1734', 'chiaretto', 'Claret'],
['7F3A02', 'Perù Tan', 'Peru Tan'],
['7F626D', 'Falco', 'Falcon'],
['7F7589', 'gangster', 'Mobster'],
['7F76D3', 'Blu Moody', 'Moody Blue'],
['7FFF00', 'certosa', 'Chartreuse'],
['7FFFD4', 'Acquamarina', 'Acquamarina'],
['800000', 'bordò', 'Bordeaux', 'Marrone'],
['800020', 'Borgogna', 'Borgogna'],
['800B47', 'Rosa mugo ciliegia', 'Rose Bud Cherry'],
['801818', 'Rosso Falun', 'Falu Red'],
['80341F', 'Pettirosso', 'Red Robin'],
['803790', 'Viola vivido', 'Vivid Violet'],
['80461B', 'Ruggine', 'Russet'],
['807E79', 'Frate Grey', 'Friar Gray'],
['808000', 'Verde oliva', 'Olive'],
['808080', 'Grigio 50%', 'Grigio'],
['80B3AE', 'Corrente del Golfo', 'Gulf Stream'],
['80B3C4', 'Ghiacciaio', 'Glacier'],
['80CCEA', 'Gabbiano', 'Seagull'],
['81422C', 'Noce moscata', 'Nutmeg'],
['816E71', 'Rosa piccante', 'Spicy Pink'],
['817377', 'Imperatrice', 'Empress'],
['819885', 'Verde spagnolo', 'Spanish Green'],
['826F65', 'Duna di sabbia', 'Sand Dune'],
['828685', 'Fumo di pistole', 'Gunsmoke'],
['828F72', 'Corazzata grigio', 'Battleship Gray'],
['831923', 'Merlot', 'Merlot'],
['837050', 'Ombra', 'Shadow'],
['83AA5D', 'Chelsea Cetriolo', 'Chelsea Cucumber'],
['83D0C6', 'Montecarlo', 'Monte Carlo'],
['843179', 'prugna', 'Plum'],
['84A0A0', 'Nonna Smith', 'Granny Smith'],
['8581D9', 'Blu Chetwode', 'Chetwode Blue'],
['858470', 'Bandicoot', 'Bandicoot'],
['859FAF', 'Bali H Ai', 'Bali Hai'],
['85C4CC', 'Mezzo cotto', 'Half Baked'],
['860111', 'diavolo Rosso', 'Red Devil'],
['863C3C', 'Loto', 'Lotus'],
['86483C', 'ironstone', 'Ironstone'],
['864D1E', 'Tiro al toro', 'Bull Shot'],
['86560A', 'chiodo arrugginito', 'Rusty Nail'],
['868974', 'Amaro', 'Bitter'],
['86949F', 'Grigio Reggente', 'Regent Gray'],
['871550', 'Discoteca', 'Disco'],
['87756E', 'Americano', 'Americano'],
['877C7B', 'uragano', 'Hurricane'],
['878D91', 'Oslo Grey', 'Oslo Gray'],
['87A96B', 'Asparago', 'Asparago'],
['87AB39', 'Sushi', 'Sushi'],
['884DA7', 'Ametista', 'Ametista'],
['885342', 'Mix piccante', 'Spicy Mix'],
['886221', 'curvo', 'Kumera'],
['888387', 'Suva Grey', 'Suva Gray'],
['888D65', 'Avocado', 'Avocado'],
['893456', 'Cammello', 'Camelot'],
['893843', 'Rosa solido', 'Solid Pink'],
['894367', 'Cannone Rosa', 'Cannon Pink'],
['897D6D', 'reel', 'Makara'],
['8A3324', "Terra d'ombra bruciata", 'Terra bruciata'],
['8A73D6', 'Vero V', 'True V'],
['8A8360', 'Torrente argilla', 'Clay Creek'],
['8A8389', 'Monsone', 'Monsoon'],
['8A8F8A', 'Pila', 'Stack'],
['8AB9F1', 'Blu Jordy', 'Jordy Blue'],
['8B00FF', 'Viola elettrico', 'Electric Violet'],
['8B0723', 'Monarca', 'Monarch'],
['8B6B0B', 'Raccolto di mais', 'Corn Harvest'],
['8B8470', 'Oliva Foschia', 'Olive Haze'],
['8B847E', 'Goletta', 'Schooner'],
['8B8680', 'Grigio naturale', 'Natural Gray'],
['8B9C90', 'Mantello', 'Mantle'],
['8B9FEE', 'Portage', 'Portage'],
['8BA690', 'Invidia', 'Envy'],
['8BA9A5', 'Cascata', 'Cascade'],
['8BE6D8', 'corrente di ritorno', 'Riptide'],
['8C055E', 'Cardinale Rosa', 'Cardinal Pink'],
['8C472F', 'Albero mulo', 'Mule Fawn'],
['8C5738', 'Clay Potter', 'Potters Clay'],
['8C6495', 'Rosa alla moda', 'Trendy Pink'],
['8D0226', 'Paprica', 'Paprika'],
['8D3D38', 'Marrone Sanguino', 'Sanguine Brown'],
['8D3F3F', 'Tosca', 'Tosca'],
['8D7662', 'Cemento', 'Cement'],
['8D8974', 'Granito verde', 'Granite Green'],
['8D90A1', 'Lamantino', 'Manatee'],
['8DA8CC', 'Polo blu', 'Polo Blue'],
['8E0000', 'Bacca rossa', 'Red Berry'],
['8E4D1E', 'Corda', 'Rope'],
['8E6F70', 'Oppio', 'Opium'],
['8E775E', 'Domino', 'Domino'],
['8E8190', 'Mamba', 'Mamba'],
['8EABC1', 'Nepal', 'Nepal'],
['8F00FF', 'Viola', 'Viola'],
['8F021C', 'Pohutukawa', 'Pohutukawa'],
['8F3E33', 'Il Salva', 'El Salva'],
['8F4B0E', 'poppa', 'Korma'],
['8F8176', 'Scoiattolo', 'Squirrel'],
['8F8F8F', 'Grigio 40%', 'Grigio 40%'],
['8FBC8F', 'Verde marino scuro', 'Verde marino scuro'],
['8FD6B4', 'Vista Blu', 'Vista Blue'],
['900020', 'Borgogna', 'Burgundy'],
['901E1E', 'Vecchio mattone', 'Old Brick'],
['907874', 'Canapa', 'Hemp'],
['907B71', 'Gelo di mandorla', 'Almond Frost'],
['908435', 'Beige Oliva Chiaro', 'Beige Oliva Chiaro'],
['908D39', 'Sicomoro', 'Sycamore'],
['918151', 'Catrame scuro', 'Catrame scuro'],
['92000A', 'Sangria', 'Sangria'],
['924321', 'Cumino', 'Cumin'],
['926F5B', 'Castoro', 'Beaver'],
['928573', 'Muro di pietra', 'Stonewall'],
['928590', 'Venere', 'Venus'],
['9370DB', 'Viola medio', 'Medium Purple'],
['93C572', 'Pistacchio', 'Pistacchio'],
['93CCEA', 'Fiordaliso', 'Cornflower'],
['93DFB8', 'Alghe verdi', 'Algae Green'],
['944747', 'Ruggine di rame', 'Copper Rust'],
['948771', 'Arrowtown', 'Arrowtown'],
['950015', 'Scarlatto', 'Scarlett'],
['956387', 'Strikemaster', 'Strikemaster'],
['959396', 'Nebbia di montagna', 'Mountain Mist'],
['960018', 'Carminio', 'Carmine'],
['964B00', 'Marrone', 'Marrone'],
['967059', 'Pelle', 'Leather'],
['9678B6', 'La maestà di Purple Mountain', "Purple Mountain's Majesty"],
['967BB6', 'Viola lavanda', 'Lavender Purple'],
['96A8A1', 'Peltro', 'Pewter'],
['96BBAB', 'Verde Estate', 'Summer Green'],
['96DED1', 'Light Robin Egg', 'Uovo di pettirosso chiaro'],
['97605D', 'A Chico', 'Au Chico'],
['9771B5', 'Glicine', 'Wisteria'],
['97CD2D', 'Atlantide', 'Atlantis'],
['983D61', 'Vino rosso', 'Vin Rouge'],
['986960', 'Castagno scuro', 'Castagno scuro'],
['9874D3', 'Lilla Bush', 'Lilac Bush'],
['987654', 'Marrone pastello', 'Marrone pastello'],
['98777B', 'Bazar', 'Bazaar'],
['98811B', 'tenuta', 'Hacienda'],
['988D77', 'Oyster pallido', 'Pale Oyster'],
['98FF98', 'Verde menta', 'Menta verde'],
['990066', 'Melanzana', 'Melanzane fresche'],
['991199', 'Viola melanzana', 'Melanzane viola'],
['991613', 'Tamarillo', 'Tamarillo'],
['991B07', 'Totem', 'Totem Pole'],
['993300', 'Marrone rosso', 'Marrone rosso'],
['993366', 'Malva', 'Malva'],
['996666', 'Malva chiaro', 'Rose di rame'],
['9966CC', 'Ametista', 'Amethyst'],
['997A8D', 'Rosa Mountbatten', 'Mountbatten Pink'],
['9999CC', 'Campana blu', 'Blue Bell'],
['99CBFF', 'Celeste', 'Celeste'],
['99FFCC', 'Turchese pallido', 'Turchese pallido'],
['9A3820', 'Pratiria Sabbia', 'Prairie Sand'],
['9A6E61', 'Crostini', 'Toast'],
['9A9577', 'Gurkha', 'Gurkha'],
['9AB973', 'Olivina', 'Olivina'],
['9AC2B8', 'Ombra Verde', 'Shadow Green'],
['9B4703', 'Oregon', 'Oregon'],
['9B9E8F', 'Citronella', 'Lemon Grass'],
['9C3336', 'Stiletto', 'Stiletto'],
['9D5616', 'Abbronzatura hawaiana', 'Hawaiian Tan'],
['9DACB7', 'Grigio oro', 'Gull Gray'],
['9DC209', 'Pistacchio', 'Pistachio'],
['9DE093', 'Nonna Smith mela', 'Granny Smith Apple'],
['9DE5FF', 'Anakiwa', 'Anakiwa'],
['9E5302', 'Gemma del Chelsea', 'Chelsea Gem'],
['9E5B40', 'Pelle di seppia', 'Sepia Skin'],
['9EA587', 'saggio', 'Sage'],
['9EA91F', 'limone', 'Citron'],
['9EB1CD', 'Blu Rocca', 'Rock Blue'],
['9EDEE0', 'Gloria mattutina', 'Morning Glory'],
['9F00FF', 'Viola chiaro', 'Viola chiaro'],
['9F381D', 'Cognac', 'Cognac'],
['9F821C', 'Barriera Corallina Oro', 'Reef Gold'],
['9F9F9C', 'Polvere di stelle', 'Star Dust'],
['9FA0B1', 'Babbo Natale grigio', 'Santas Gray'],
['9FD7D3', 'Sinbad', 'Sinbad'],
['9FDD8C', 'Feijoa', 'Feijoa'],
['A02712', 'Tabasco', 'Tabasco'],
['A1750D', 'Rum imbottito', 'Buttered Rum'],
['A1ADB5', 'Colpito Grigio', 'Hit Gray'],
['A1C50A', 'agrume', 'Citrus'],
['A1DAD7', 'Isola Aqua', 'Aqua Island'],
['A1E9DE', "Foglia d'acqua", 'Water Leaf'],
['A2006D', 'Flirtare', 'Flirt'],
['A23B6C', 'Rosso', 'Rouge'],
['A26645', 'Capo Palliser', 'Cape Palliser'],
['A2AAB3', 'Castello grigio', 'Gray Chateau'],
['A2AEAB', 'Edoardo', 'Edward'],
['A3807B', 'Farlap', 'Pharlap'],
['A397B4', 'Fumo di ametista', 'Amethyst Smoke'],
['A3E3ED', 'Blu Bufera di neve', 'Blizzard Blue'],
['A4A49D', 'Delta', 'Delta'],
['A4A6D3', 'sognante', 'Wistful'],
['A4AF6E', 'Fumo verde', 'Green Smoke'],
['A50B5E', 'Jam di jazz', 'Jazzberry Jam'],
['A52019', 'Rosso segnale', 'Rosso segnale'],
['A59B91', 'prepotente', 'Zorba'],
['A5CB0C', 'Bahia', 'Bahia'],
['A61022', 'Rosso fuoco', 'Rosso fuoco'],
['A62F20', 'Tetto in terracotta', 'Roof Terracotta'],
['A65529', 'Paarl', 'Paarl'],
['A68B5B', "Mais d'orzo", 'Barley Corn'],
['A69279', 'Asino Marrone', 'Donkey Brown'],
['A6A29A', 'alba', 'Dawn'],
['A6FBB2', 'Verde menta chiaro', 'Verde menta chiaro'],
['A72525', 'Rosso messicano', 'Mexican Red'],
['A7882C', 'Oro Luxor', 'Luxor Gold'],
['A85307', 'Oro ricco', 'Rich Gold'],
['A86515', 'Sabbia di Reno', 'Reno Sand'],
['A86B6B', 'Albero di corallo', 'Coral Tree'],
['A8989B', 'Dusty Grey', 'Dusty Gray'],
['A899E6', 'Lavanda opaca', 'Dull Lavender'],
['A8A589', 'Sego', 'Tallow'],
['A8AE9C', 'offerte', 'Bud'],
['A8AF8E', 'Locusta', 'Locust'],
['A8BD9F', 'Norvegia', 'Norway'],
['A8E3BD', 'Mentola', 'Chinook'],
['A98307', 'Giallo miele', 'Giallo miele'],
['A9A491', 'Olive grigie', 'Gray Olive'],
['A9ACB6', 'alluminio', 'Aluminium'],
['A9B2C3', 'Cadetto Blu', 'Cadet Blue'],
['A9B497', 'Scisto', 'Schist'],
['A9BDBF', 'Tower Grey', 'Tower Gray'],
['A9BEF2', 'Perano', 'Perano'],
['A9C6C2', 'Opale', 'Opal'],
['AA375A', 'Shadz notte', 'Night Shadz'],
['AA4203', 'Fuoco', 'Fire'],
['AA8B5B', 'Muesli', 'Muesli'],
['AA8D6F', 'Sandalo', 'Sandal'],
['AAA5A9', 'Signora ombrosa', 'Shady Lady'],
['AAA9CD', 'Logan', 'Logan'],
['AAABB7', 'Perla filata', 'Spun Pearl'],
['AAD6E6', 'Reggente San Blu', 'Regent St Blue'],
['AAF0D1', 'Menta magica', 'Magic Mint'],
['AB0563', 'Rossetto', 'Lipstick'],
['AB3472', 'Brughiera reale', 'Royal Heath'],
['AB917A', 'Sandrift', 'Sandrift'],
['ABA0D9', 'Viola freddo', 'Cold Purple'],
['ABA196', 'mustang', 'Bronco'],
['ABCDEF', 'Azzurro Fiordaliso', 'Azzurro Fiordaliso'],
['AC8A56', 'Quercia macinata', 'Limed Oak'],
['AC91CE', 'lato est', 'East Side'],
['AC9E22', 'Zenzero al limone', 'Lemon Ginger'],
['ACA494', 'Napa', 'Napa'],
['ACA586', 'Hillary', 'Hillary'],
['ACA59F', 'Nuvoloso', 'Cloudy'],
['ACACAC', "Calice d'argento", 'Silver Chalice'],
['ACB78E', 'Palude verde', 'Swamp Green'],
['ACCBB1', 'Pioggia primaverile', 'Spring Rain'],
['ACDD4D', 'Conifera', 'Conifer'],
['ACE1AF', 'Celadon', 'Celadon'],
['AD781B', 'Mandalay', 'Mandalay'],
['ADBED1', 'Casper', 'Casper'],
['ADDFAD', 'Verde muschio', 'Moss Green'],
['ADE6C4', 'Padova', 'Padua'],
['ADFF2F', 'Verde-giallo', 'Verde giallo'],
['AE4560', 'Hippie rosa', 'Hippie Pink'],
['AE6020', 'Deserto', 'Desert'],
['AE809E', 'Bouquet', 'Bouquet'],
['AF4035', 'Carmine medio', 'Medium Carmine'],
['AF4D43', 'bocciolo di mela', 'Apple Blossom'],
['AF593E', 'Marrone Ruggine', 'Brown Rust'],
['AF8751', 'Legno deriva', 'Driftwood'],
['AF8F2C', 'alpino', 'Alpine'],
['AF9F1C', 'Fortunato', 'Lucky'],
['AFA09E', 'Martini', 'Martini'],
['AFB1B8', 'Bombay', 'Bombay'],
['AFBDD9', 'Piccione Post', 'Pigeon Post'],
['B04C6A', 'Cadillac', 'Cadillac'],
['B05D54', 'Matrice', 'Matrix'],
['B05E81', 'arazzo', 'Tapestry'],
['B06608', 'Più Tai', 'Mai Tai'],
['B09A95', 'Del Rio', 'Del Rio'],
['B0E0E6', 'Blu polvere', 'Powder Blue'],
['B0E313', 'Verme di pollice', 'Inch Worm'],
['B10000', 'Rosso brillante', 'Bright Red'],
['B14A0B', 'Vesuvio', 'Vesuvius'],
['B1610B', 'Pelle di zucca', 'Pumpkin Skin'],
['B16D52', 'Festa di Babbo Natale', 'Santa Fe'],
['B19461', 'Teak', 'Teak'],
['B1E2C1', 'Fiore Frinoso', 'Fringy Flower'],
['B1F4E7', 'Ghiacciato', 'Ice Cold'],
['B20000', 'Porpora', 'Porpora'],
['B20931', 'Shiraz', 'Shiraz'],
['B22222', 'Rosso opaco', 'Rosso mattone'],
['B2A1EA', 'Fiore Biloba', 'Biloba Flower'],
['B2B2B2', 'Grigio 30%', 'Grigio 30%'],
['B32D29', 'Papavero alto', 'Tall Poppy'],
['B35213', 'Arancione ardente', 'Fiery Orange'],
['B38007', 'Toddy caldo', 'Hot Toddy'],
['B3AF95', 'Grigio talpa', 'Taupe Gray'],
['B3C110', 'La Rioja', 'La Rioja'],
['B43332', 'Bene, leggi', 'Well Read'],
['B44668', 'Arrossire', 'Blush'],
['B4CFD3', 'Nebbia della giungla', 'Jungle Mist'],
['B57281', 'Rosa turca', 'Turkish Rose'],
['B57EDC', 'Lavanda', 'Lavender'],
['B5A27F', 'Mangusta', 'Mongoose'],
['B5B35C', 'Verde oliva', 'Olive Green'],
['B5D2CE', 'Flusso a getto', 'Jet Stream'],
['B5ECDF', 'Crociera', 'Cruise'],
['B6316C', 'Ibisco', 'Hibiscus'],
['B69D98', 'Paglia', 'Thatch'],
['B6B095', 'Heathered Grey', 'Heathered Gray'],
['B6BAA4', 'Aquila', 'Eagle'],
['B6D1EA', 'Mandrino', 'Spindle'],
['B6D3BF', 'Foglia di gomma', 'Gum Leaf'],
['B7410E', 'Ruggine', 'Rust'],
['B78E5C', 'Acque fangose', 'Muddy Waters'],
['B7A214', 'Sahara', 'Sahara'],
['B7A458', 'ricordare', 'Husk'],
['B7B1B1', 'Nobel', 'Nobel'],
['B7C3D0', 'Erica', 'Heather'],
['B7F0BE', 'Madang', 'Madang'],
['B81104', 'Rosso Milano', 'Milano Red'],
['B87333', 'Riga', 'Rame'],
['B8860B', 'Solidago scuro', 'Solidago scuro'],
['B8B56A', 'Gimblet', 'Gimblet'],
['B8C1B1', 'Primavera verde', 'Green Spring'],
['B8C25D', 'Sedano', 'Celery'],
['B8E0F9', 'Vela', 'Sail'],
['B94E48', 'Castagna', 'Chestnut'],
['B95140', 'Chiocciola', 'Crail'],
['B98D28', 'Calendula', 'Marigold'],
['B9C46A', 'Salice Selvaggio', 'Wild Willow'],
['B9C8AC', 'Allievo', 'Rainee'],
['BA0101', 'Guardia rossa', 'Guardsman Red'],
['BA450C', 'Spruzzo di roccia', 'Rock Spray'],
['BA6262', 'Rosso Tiziano', 'Rosso Tiziano'],
['BA6F1E', 'Borbone', 'Bourbon'],
['BA7F03', 'Oro pirata', 'Pirate Gold'],
['BAB1A2', 'Nomade', 'Nomad'],
['BAC7C9', 'Sottomarino', 'Submarine'],
['BADBAD', 'Tè verde scuro', 'Tè verde scuro'],
['BAEEF9', 'Carlotta', 'Charlotte'],
['BB3385', 'Viola rossa media', 'Medium Red Violet'],
['BB8983', 'Brandy rosa', 'Brandy Rose'],
['BBD009', 'Rio Grande', 'Rio Grande'],
['BBD7C1', 'Navigare', 'Surf'],
['BCC9C2', 'Polvere di cenere', 'Powder Ash'],
['BD5E2E', 'Toscana', 'Tuscany'],
['BD8E80', 'Rosso opaco chiaro', 'Rosso mattone chiaro'],
['BD978E', 'Sabbie mobili', 'Quicksand'],
['BDB1A8', 'Seta', 'Silk'],
['BDB2A1', 'Malta', 'Malta'],
['BDB3C7', 'Chatelle', 'Chatelle'],
['BDB76B', 'Cachi scuro', 'Kaki scuro'],
['BDBBD7', 'Grigio lavanda', 'Lavender Gray'],
['BDBDC6', 'Grigio francese', 'French Gray'],
['BDC8B3', "Frassino d'argilla", 'Clay Ash'],
['BDC9CE', 'Lobloso', 'Loblolly'],
['BDEDFD', 'Passo Francese', 'French Pass'],
['BEA6C3', 'Tonalità di Londra', 'London Hue'],
['BEB5B7', 'Cigno rosa', 'Pink Swan'],
['BEBD7F', 'Verdastro Beige', 'Beige Verdastro'],
['BEDE0D', 'fuoco', 'Fuego'],
['BF5500', 'Rosa di sharon', 'Rose of Sharon'],
['BFB8B0', 'Marea', 'Tide'],
['BFBED8', 'Blu Haze', 'Blue Haze'],
['BFC1C2', "Sabbia d'argento", 'Silver Sand'],
['BFC921', 'Torta alla limetta', 'Key Lime Pie'],
['BFDBE2', 'ziggurat', 'Ziggurat'],
['BFFF00', 'Calce', 'Lime'],
['C0007F', 'Vinaccia', 'Vinaccia'],
['C02B18', 'Thunderbird', 'Thunderbird'],
['C04000', 'Mogano', 'Mogano'],
['C04737', 'Mojo', 'Mojo'],
['C08081', 'Vecchia rosa', 'Old Rose'],
['C0C0C0', 'Argento', 'Argento'],
['C0D3B9', 'Foglia pallida', 'Pale Leaf'],
['C0D8B6', 'Verde Pixie', 'Pixie Green'],
['C1440E', 'Tia Maria', 'Tia Maria'],
['C154C1', 'Rosa fucsia', 'Fuchsia Pink'],
['C1A004', 'Oro Buddha', 'Buddha Gold'],
['C1B7A4', 'Nascondere Bisonte', 'Bison Hide'],
['C1BAB0', 'Tè', 'Tea'],
['C1BECD', 'Vestito grigio', 'Gray Suit'],
['C1D7B0', 'Germoglio', 'Sprout'],
['C1F07C', 'Sulu', 'Sulu'],
['C26B03', 'Indocina', 'Indochine'],
['C2955D', 'Spago', 'Twine'],
['C2B280', 'ecru', 'Ecru'],
['C2BDB6', 'Seme di cotone', 'Cotton Seed'],
['C2CAC4', 'Pomice', 'Pumice'],
['C2E8E5', 'Ghiaccio frastagliato', 'Jagged Ice'],
['C32148', 'Risciacquo marrone', 'Maroon Flush'],
['C3B091', 'gamba', 'Kaki', 'Cachi indiano'],
['C3BFC1', 'Pallido ardesia', 'Pale Slate'],
['C3C3BD', 'Nickel grigio', 'Gray Nickel'],
['C3CDE6', 'Grigio pervinca', 'Periwinkle Gray'],
['C3D1D1', 'Tiara', 'Tiara'],
['C3DDF9', 'Blu tropicale', 'Tropical Blue'],
['C41E3A', 'Rosso cardinale', 'Cardinale'],
['C45655', 'Marrone Wuzzy sfocato', 'Fuzzy Wuzzy Brown'],
['C45719', 'Arancione ruvido', 'Orange Roughy'],
['C4C4BC', 'Nebbia grigia', 'Mist Gray'],
['C4D0B0', 'Coriandolo', 'Coriander'],
['C4F4EB', 'Tulipano alla menta', 'Mint Tulip'],
['C54B8C', 'Gelso', 'Mulberry'],
['C59922', 'Pepita', 'Nugget'],
['C5994B', "ciuffo d'erba", 'Tussock'],
['C5DBCA', 'Nebbia marina', 'Sea Mist'],
['C5E17A', 'Giallo verde', 'Yellow Green'],
['C62D42', 'Rosso mattone', 'Brick Red'],
['C6726B', 'Contessa', 'Contessa'],
['C69191', 'Rosa orientale', 'Oriental Pink'],
['C6A664', 'Giallo sabbia', 'Giallo sabbia'],
['C6A84B', 'ruotare', 'Roti'],
['C6C3B5', 'Cenere', 'Ash'],
['C6C8BD', 'Canguro', 'Kangaroo'],
['C6E610', 'Las Palmas', 'Las Palmas'],
['C7031E', 'Monza', 'Monza'],
['C71585', 'Rosso violaceo', 'Red Violet'],
['C7BCA2', 'Barriera corallina', 'Coral Reef'],
['C7C1FF', 'Melassa', 'Melrose'],
['C7C4BF', 'Nuvola', 'Cloud'],
['C7C9D5', 'Fantasma', 'Ghost'],
['C7CD90', 'radura del pino', 'Pine Glade'],
['C7DDE5', 'Botticelli', 'Botticelli'],
['C80815', 'Rosso veneziano', 'Rosso veneziano'],
['C88A65', 'Ottone antico', 'Antique Brass'],
['C8A2C8', 'piccolo', 'Lilla', 'Lilla'],
['C8A528', 'Scimmia Pokey', 'Hokey Pokey'],
['C8AABF', 'Giglio', 'Lily'],
['C8B568', 'Laser', 'Laser'],
['C8E3D7', 'Bordo acqua', 'Edgewater'],
['C96323', 'Pifferaio', 'Piper'],
['C99415', 'Pizza', 'Pizza'],
['C9A0DC', 'Glicine', 'Glicine leggero'],
['C9B29B', 'Polvere di rodeo', 'Rodeo Dust'],
['C9B35B', 'Sundance', 'Sundance'],
['C9B93B', 'Verde Conti', 'Earls Green'],
['C9C0BB', "Ruggine d'argento", 'Silver Rust'],
['C9D9D2', 'Conchiglia', 'Conch'],
['C9FFA2', 'scogliera', 'Reef'],
['C9FFE5', 'Azzurro Eroe', 'Aero Blue'],
['CA3435', 'Mogano a filo', 'Flush Mahogany'],
['CABB48', 'Curcuma', 'Turmeric'],
['CADABA', 'Grigio tè verde', 'Grigio tè verde'],
['CADCD4', 'Parigi Bianco', 'Paris White'],
['CAE00D', 'Limone amaro', 'Bitter Lemon'],
['CAE6DA', 'Scettico', 'Skeptic'],
['CB8FA9', 'Viola', 'Viola'],
['CBCAB6', 'Foggy Grey', 'Foggy Gray'],
['CBD3B0', 'Nebbia verde', 'Green Mist'],
['CBDBD6', 'Nebulosa', 'Nebula'],
['CC0000', 'Rosso corsa', 'Rosso corsa'],
['CC3333', 'Rosso persiano', 'Persian Red'],
['CC5500', 'Rosso aragosta', 'Arancia bruciata'],
['CC7722', 'Rottame', 'Ocra'],
['CC8899', 'Incarnato prugna', 'chip'],
['CC9966', 'Ottone antico', 'Ottone antico'],
['CCCAA8', 'Verde cardo', 'Thistle Green'],
['CCCCFF', 'pervinca', 'Pervinca', 'Pervinca'],
['CCFF00', 'Lime', 'Calce elettrica'],
['CD5700', 'voluto', 'Tenné', 'Tenn'],
['CD5C5C', 'Castagno', 'Rosa castagna'],
['CD7F32', 'Bronzo', 'Bronzo'],
['CD8429', 'Punzone Brandy', 'Brandy Punch'],
['CD853F', 'Marrone chiaro', 'Marrone chiaro'],
['CDF4FF', 'Onahau', 'Onahau'],
['CE3018', 'Fragola Rosso', 'Rosso fragola'],
['CEB98F', 'Acetosa Marrone', 'Sorrell Brown'],
['CEBABA', 'Tacchino freddo', 'Cold Turkey'],
['CEC291', 'Yuma', 'Yuma'],
['CEC7A7', 'cinese', 'Chino'],
['CFA39D', 'Eunry', 'Eunry'],
['CFB53B', 'Oro vecchio', 'Oro vecchio'],
['CFDCCF', 'Tasman', 'Tasman'],
['CFE5D2', 'Surf cresta', 'Surf Crest'],
['CFF9F3', 'Colibrì', 'Humming Bird'],
['CFFAF4', 'Scandalo', 'Scandal'],
['D05F04', 'Fase rossa', 'Red Stage'],
['D06DA1', 'Luppolo', 'Hopbush'],
['D07D12', 'Meteora', 'Meteor'],
['D0AFAE', 'Grigio rosso chiaro', 'Grigio rosso chiaro'],
['D0BEF8', 'Profumo', 'Perfume'],
['D0C0E5', 'Preludio', 'Prelude'],
['D0F0C0', 'Tè verde', 'Tè verde'],
['D18F1B', 'Geebung', 'Geebung'],
['D1BEA8', 'Vaniglia', 'Vanilla'],
['D1C6B4', 'Ambra morbida', 'Soft Amber'],
['D1D2CA', 'Celeste', 'Celeste'],
['D1D2DD', 'Mischka', 'Mischka'],
['D1E231', 'soldi', 'Pera', 'Pera'],
['D21F1B', 'Rosso pompeiano', 'Rosso pompeiano'],
['D2691E', 'Cioccolato', 'Cannella calda'],
['D27D46', 'Terra di Siena cruda', 'Raw Sienna'],
['D29EAA', 'Carey Pink', 'Careys Pink'],
['D2B48C', 'Catrame', 'così'],
['D2D2D2', 'Grigio 20%', 'Grigio 20%'],
['D2DA97', 'Deco', 'Deco'],
['D2F6DE', 'Romanticismo blu', 'Blue Romance'],
['D2F8B0', 'Pettegolezzo', 'Gossip'],
['D3305D', 'Azalea', 'Azalea'],
['D3CBBA', 'Sisal', 'Sisal'],
['D3CDC5', 'turbine', 'Swirl'],
['D47494', 'Fascino', 'Charm'],
['D4B6AF', 'Conchiglia a vongola', 'Clam Shell'],
['D4BF8D', 'Cannuccia', 'Straw'],
['D4C4A8', 'Akaroa', 'Akaroa'],
['D4CD16', 'Fiore di uccello', 'Bird Flower'],
['D4D7D9', 'Ferro', 'Iron'],
['D4DFE2', 'scaldabagno', 'Geyser'],
['D4E2FC', 'Falchi blu', 'Hawkes Blue'],
['D54600', 'Granatiere', 'Grenadier'],
['D591A4', 'Posso posso', 'Can Can'],
['D59A6F', 'Whisky', 'Whiskey'],
['D5D195', 'Nocciola invernale', 'Winter Hazel'],
['D5F6E3', 'Mela nonna', 'Granny Apple'],
['D69188', 'Il mio rosa', 'My Pink'],
['D6C562', 'macchia', 'Tacha'],
['D6CEF6', 'Moonraker', 'Moon Raker'],
['D6D6D1', 'Grigio cannotto', 'Quill Gray'],
['D6FFDB', 'Menta Snowy', 'Snowy Mint'],
['D7837F', 'New York Rosa', 'New York Pink'],
['D7C498', 'Pavlova', 'Pavlova'],
['D7D0FF', 'dente', 'Fog'],
['D84437', 'Valenza', 'Valencia'],
['D87C63', 'japonica', 'Japonica'],
['D8BFD8', 'Cardo', 'Cardo'],
['D8C2D5', 'Maverick', 'Maverick'],
['D8FCFA', 'Schiuma', 'Foam'],
['D94972', 'Cabaret', 'Cabaret'],
['D99376', 'Sabbia ardente', 'Burning Sand'],
['D9B99B', 'Cammeo', 'Cameo'],
['D9D6CF', 'Lupo Legna', 'Timberwolf'],
['D9DCC1', 'Tana', 'Tana'],
['D9E4F5', "Collega l'acqua", 'Link Water'],
['D9F7FF', 'Mabel', 'Mabel'],
['DA3287', 'ciliegia', 'Cerise'],
['DA5B38', 'Pisello di fiamma', 'Flame Pea'],
['DA6304', 'Bambù', 'Bamboo'],
['DA6A41', 'Damasco rosso', 'Red Damask'],
['DA70D6', 'Orchidea', 'Orchidea'],
['DA8A67', 'Campo di rame', 'Copperfield'],
['DAA520', 'Solidago', 'Erba dorata'],
['DABAD0', 'Pallido lavanda', 'Lavanda pallido'],
['DABDAB', 'Marrone sabbia chiaro', 'Marrone sabbia chiaro'],
['DAECD6', 'zañahary', 'Zanah'],
['DAF4F0', 'Iceberg', 'Iceberg'],
['DAFAFF', 'Baia di Ostriche', 'Oyster Bay'],
['DB244F', 'Rosa medio', 'Rosa medio'],
['DB5079', 'Mirtillo', 'Cranberry'],
['DB7093', 'Light violet red', 'Rosso violetto chiaro'],
['DB9690', 'Petite Orchidea', 'Petite Orchid'],
['DB995E', 'Di Serria', 'Di Serria'],
['DBDBDB', 'Alto', 'Alto'],
['DBFFF8', 'Menta glassata', 'Frosted Mint'],
['DC143C', 'Cremisi', 'Cremisi'],
['DC4333', 'Punzone', 'Punch'],
['DCB20C', 'Galliano', 'Galliano'],
['DCB4BC', 'Fiorire', 'Blossom'],
['DCD747', 'canniccio', 'Wattle'],
['DCD9D2', 'Westar', 'Westar'],
['DCDCDC', 'Gainsboro', 'Gainsboro'],
['DCDDCC', 'Nebbia lunare', 'Moon Mist'],
['DCEDB4', 'Cappero', 'Caper'],
['DCF0EA', 'Cigni giù', 'Swans Down'],
['DDADAF', 'Castagno chiaro', 'Castagno chiaro'],
['DDD6D5', 'Caffè svizzero', 'Swiss Coffee'],
['DDF9F1', 'Ghiaccio bianco', 'White Ice'],
['DE3163', 'Ciliegia', 'Cerise Red'],
['DE6360', 'romano', 'Roman'],
['DEA681', 'Tumbleweed', 'Tumbleweed'],
['DEBA13', "Suggerimenti d'oro", 'Gold Tips'],
['DEC196', 'Brandy', 'Brandy'],
['DECBC6', 'Cialda', 'Wafer'],
['DED4A4', 'Alberello', 'Sapling'],
['DED717', 'Crespino', 'Barberry'],
['DEE5C0', 'Verde berillo', 'Beryl Green'],
['DEF5FF', 'Blu pattini', 'Pattens Blue'],
['DF73FF', 'Eliotropo', 'Eliotropio'],
['DFBE6F', 'Apache', 'Apache'],
['DFCD6F', 'fenina', 'Chenin'],
['DFCFDB', 'Lola', 'Lola'],
['DFECDA', 'Brook salice', 'Willow Brook'],
['DFFF00', 'Giallo Chartreuse', 'Chartreuse Yellow'],
['E0AFEE', 'Fucsia Bordesto Lillato', 'Fucsia Bordesto Lillato'],
['E0B0FF', 'malva', 'Mauve'],
['E0B646', 'Anzac', 'Anzac'],
['E0B974', 'Raccolto Oro', 'Harvest Gold'],
['E0C095', 'Calicò', 'Calico'],
['E0FFFF', 'Carta da zucchero', 'Bambina blu'],
['E16865', 'Sungilo', 'Sunglo'],
['E1BC64', 'Equatore', 'Equator'],
['E1C0C8', 'Bagliore rosa', 'Pink Flare'],
['E1E6D6', 'Blu periglaciale', 'Periglacial Blue'],
['E1EAD4', 'Rapitore', 'Kidnapper'],
['E1F6E8', 'quando il', 'Tara'],
['E25465', 'Mandy', 'Mandy'],
['E2725B', 'Terracotta', 'Terracotta'],
['E28913', "Campana d'oro", 'Golden Bell'],
['E292C0', 'Scioccante', 'Shocking'],
['E29418', 'marmitta', 'Dixie'],
['E29CD2', 'Orchidea chiara', 'Light Orchid'],
['E2D8ED', 'Tabacco da fiuto', 'Snuff'],
['E2EBED', 'Mistico', 'Mystic'],
['E2F3EC', 'Mela verde', 'Apple Green'],
['E30B5C', 'Lampone', 'clamore'],
['E32636', 'Cremisi Alizarina', 'Alizarin Crimson'],
['E34234', 'Cinabro', 'Cinnabar'],
['E3BEBE', 'Caverna Rosa', 'Cavern Pink'],
['E3F5E1', 'Menta piperita', 'Peppermint'],
['E3F988', 'Mindaro', 'Mindaro'],
['E47698', 'Fardello Intenso', 'Deep Blush'],
['E49B0F', 'gamboge', 'Gamboge'],
['E4C2D5', 'Melania', 'Melanie'],
['E4CFDE', 'crepuscolo', 'Twilight'],
['E4D1C0', 'osso', 'Bone'],
['E4D422', 'Girasole', 'Sunflower'],
['E4D5B7', 'Grana Marrone', 'Grain Brown'],
['E4D69B', 'Zombie', 'Zombie'],
['E4E5E0', 'Grigio Cenere', 'Grigio cenere'],
['E4F6E7', 'Frostee', 'Frostee'],
['E4FFD1', 'Flurry di neve', 'Snow Flurry'],
['E52B50', 'Amaranto', 'amaranto'],
['E5841B', 'gusto', 'Zest'],
['E5BE01', 'Giallo segnale', 'Giallo segnale'],
['E5CCC9', 'Tempesta di sabbia', 'Dust Storm'],
['E5D7BD', 'Bianco stellato', 'Stark White'],
['E5D8AF', 'Hampton', 'Hampton'],
['E5E0E1', 'Buongiorno', 'Bon Jour'],
['E5E4E2', 'Platino', 'Platino'],
['E5E5E5', 'Mercurio', 'Mercury'],
['E5F9F6', 'Polare', 'Polar'],
['E64E03', 'Trinidad', 'Trinidad'],
['E6BE8A', 'Sabbia dorata', 'Gold Sand'],
['E6BEA5', 'Cachemire', 'Cashmere'],
['E6D7B9', 'Doppio bianco spagnolo', 'Double Spanish White'],
['E6E4D4', 'Lino satinato', 'Satin Linen'],
['E6E6FA', 'Lavanda', 'Lavanda'],
['E6F2EA', 'Arpa', 'Harp'],
['E6F8F3', 'Fuori verde', 'Off Green'],
['E6FFE9', 'Suggerimento di verde', 'Hint of Green'],
['E6FFFF', 'Tranquillo', 'Tranquil'],
['E75480', 'Rosa scuro', 'Rosa scuro'],
['E77200', 'Tango di Mango', 'Mango Tango'],
['E7730A', 'Cristina', 'Christine'],
['E79F8C', 'Tonys Rosa', 'Tonys Pink'],
['E79FC4', 'poeta', 'Kobi'],
['E7BCB4', 'Rosa nebbia', 'Rose Fog'],
['E7BF05', 'Mais', 'Corn'],
['E7CD8C', 'stucco', 'Putty'],
['E7ECE6', 'Infermiera grigia', 'Gray Nurse'],
['E7F8FF', 'Giglio Bianco', 'Lily White'],
['E7FEFF', 'bolle', 'Bubbles'],
['E89928', 'Fuoco cespuglio', 'Fire Bush'],
['E8B9B3', 'Shilo', 'Shilo'],
['E8E0D5', 'Perla Bush', 'Pearl Bush'],
['E8EBE0', 'Verde Bianco', 'Green White'],
['E8F1D4', 'Bianco cromato', 'Chrome White'],
['E8F2EB', 'Gin', 'Gin'],
['E8F5F2', 'Acqua spremere', 'Aqua Squeeze'],
['E96E00', 'Clementina', 'Clementine'],
['E97451', 'Terra di Siena', 'Terra di Siena bruciata'],
['E97C07', 'Tahiti Oro', 'Tahiti Gold'],
['E9967A', 'Salmone scuro', 'Salmone scuro'],
['E9CECD', 'Ostrica Rosa', 'Oyster Pink'],
['E9D75A', 'Coriandoli', 'Confetti'],
['E9E3E3', 'Riflusso', 'Ebb'],
['E9F8ED', 'ottomano', 'Ottoman'],
['E9FFFD', 'Giornata limpida', 'Clear Day'],
['EA88A8', 'Carissma', 'Carissma'],
['EAAE69', 'Porsche', 'Porsche'],
['EAB33B', 'Albero di tulipani', 'Tulip Tree'],
['EAC674', 'Rob Roy', 'Rob Roy'],
['EADAB8', 'Rafia', 'Raffia'],
['EAE8D4', 'Roccia Bianca', 'White Rock'],
['EAF6EE', 'pennacchio', 'Panache'],
['EAF6FF', 'Solitudine', 'Solitude'],
['EAF9F5', 'Primavera Acqua', 'Aqua Spring'],
['EAFFFE', 'Rugiada', 'Dew'],
['EB9373', 'Albicocca', 'Apricot'],
['EBB55F', 'Fulvo', 'Fulvo'],
['EBC2AF', 'zinnwaldite', 'Zinnwaldite'],
['ECA927', 'Carburante giallo', 'Fuel Yellow'],
['ECC54E', 'Ronchi', 'Ronchi'],
['ECC7EE', 'Lilla francese', 'French Lilac'],
['ECCDB9', 'Giusto', 'Just Right'],
['ECE090', 'Riso selvatico', 'Wild Rice'],
['ECEBBD', 'Verde caduta', 'Fall Green'],
['ECEBCE', 'Attese Speciali', 'Aths Special'],
['ECF245', 'Starship', 'Starship'],
['ED0A3F', 'Fiocco rosso', 'Red Ribbon'],
['ED7465', 'Aragosta', 'Aragosta'],
['ED7A1C', 'Tango', 'Tango'],
['ED9121', 'Arancia carota', 'Carrot Orange'],
['ED989E', 'Rosa mare', 'Sea Pink'],
['EDB381', 'heelpiece', 'Tacao'],
['EDC9AF', 'Sabbia del deserto', 'Desert Sand'],
['EDCDAB', 'Pancho', 'Pancho'],
['EDDCB1', 'camoscio', 'Chamois'],
['EDEA99', 'Primula', 'Primrose'],
['EDF5DD', 'brina', 'Frost'],
['EDF5F5', 'Aqua Haze', 'Aqua Haze'],
['EDF6FF', 'Zumthor', 'Zumthor'],
['EDF9F1', 'Narvik', 'Narvik'],
['EDFC84', 'Caprifoglio', 'Honeysuckle'],
['EE82EE', 'Lavanda magenta', 'Lavender Magenta'],
['EEC1BE', 'Bellezza Cespuglio', 'Beauty Bush'],
['EED794', 'gessoso', 'Chalky'],
['EED9C4', 'Mandorla', 'Almond'],
['EEDC82', 'Lino', 'Flax'],
['EEDEDA', 'Bizzarro', 'Bizarre'],
['EEE3AD', 'Doppio bianco coloniale', 'Double Colonial White'],
['EEEEE8', 'Carrara', 'Cararra'],
['EEEF78', 'Manz', 'Manz'],
['EEF0C8', 'Sabbie di Tahuna', 'Tahuna Sands'],
['EEF0F3', 'Grigio di Atene', 'Athens Gray'],
['EEF3C3', 'zanna', 'Tusk'],
['EEF4DE', 'mocassino', 'Loafer'],
['EEF6F7', 'Bianco Catania', 'Catskill White'],
['EEFDFF', 'Blu crepuscolo', 'Twilight Blue'],
['EEFF9A', 'Giunchiglia', 'Jonquil'],
['EEFFE2', 'Fiore di riso', 'Rice Flower'],
['EF863F', 'Giaffa', 'Jaffa'],
['EFEFEF', 'Grigio 10%', 'Galleria'],
['EFF2F3', 'Porcellana', 'Porcelain'],
['F091A9', 'Mauvelo', 'Mauvelous'],
['F0D52D', "Sogno d'oro", 'Golden Dream'],
['F0DB7D', 'Sabbia dorata', 'Golden Sand'],
['F0DC82', 'Camoscio', 'pelle di bufalo'],
['F0E2EC', 'prima', 'Prim'],
['F0E68C', 'Kaki chiaro', 'Cachi'],
['F0EEFD', 'selago', 'Selago'],
['F0EEFF', 'Bianco Titano', 'Titan White'],
['F0F8FF', 'Blu Alice', 'Alice Blue'],
['F0FCEA', 'Feta', 'Feta'],
['F18200', "Goccia d'oro", 'Gold Drop'],
['F19BAB', 'Svegliarsi', 'Wewak'],
['F1E788', 'Sahara Sabbia', 'Sahara Sand'],
['F1E9D2', 'Pergamena', 'Parchment'],
['F1E9FF', 'Gesso blu', 'Blue Chalk'],
['F1EEC1', 'Come Julep', 'Mint Julep'],
['F1F1F1', 'Conchiglia', 'Seashell'],
['F1F7F2', 'saline', 'Saltpan'],
['F1FFAD', 'di marea', 'Tidal'],
['F1FFC8', 'Chiffon', 'Chiffon'],
['F2552A', 'Fenicottero', 'Flamingo'],
['F28500', 'Mandarino', 'Tangerine'],
['F2C3B2', 'Mandrini Rosa', 'Mandys Pink'],
['F2F2F2', 'Calcestruzzo', 'Concrete'],
['F2F3F4', 'Bianco Anti Flash', 'Bianco Anti Flash'],
['F2FAFA', 'Spremitura nero', 'Black Squeeze'],
['F34723', 'Melograno', 'Pomegranate'],
['F3AD16', 'Ranuncolo', 'Buttercup'],
['F3D69D', 'New Orleans', 'New Orleans'],
['F3D9DF', 'Gelato alla vaniglia', 'Vanilla Ice'],
['F3E7BB', 'Sidecar', 'Sidecar'],
['F3E9E5', 'Alba Rosa', 'Dawn Pink'],
['F3EDCF', 'Campo di grano', 'Wheatfield'],
['F3FB62', 'Canarino', 'Canary'],
['F3FBD4', 'Orinoco', 'Orinoco'],
['F3FFD8', 'Carla', 'Carla'],
['F400A1', 'Fucsia', 'Hollywood Cherry'],
['F4A460', 'Sabbia', 'Marrone sabbia'],
['F4C430', 'Zafferano', 'Zafferano'],
['F4D81C', 'Limone maturo', 'Ripe Lemon'],
['F4EBD3', 'Un paradiso', 'Janna'],
['F4F0EC', 'Isabella', 'Isabella'],
['F4F2EE', 'pampa', 'Pampas'],
['F4F4F4', 'Sabbia selvaggia', 'Wild Sand'],
['F4F8FF', 'Zircone', 'Zircon'],
['F57584', 'Goccia', 'Froly'],
['F5C85C', 'Crema può', 'Cream Can'],
['F5C999', 'Manhattan', 'Manhattan'],
['F5D5A0', 'Granoturco', 'Maize'],
['F5DEB3', 'Grano', 'Grano'],
['F5E7A2', 'Sandwisp', 'Sandwisp'],
['F5E7E2', 'Pentola Pourri', 'Pot Pourri'],
['F5E9D3', 'Bianco Albescente', 'Albescent White'],
['F5EDEF', 'Pesca morbida', 'Soft Peach'],
['F5F3E5', 'Ecru bianco', 'Ecru White'],
['F5F5DC', 'Beige', 'Beige'],
['F5F5F5', 'Bianco Fumo', 'Bianco Fumo'],
['F5FB3D', 'Fizz dorati', 'Golden Fizz'],
['F5FFBE', 'Menta australiana', 'Australian Mint'],
['F64A8A', 'Rosa francese', 'French Rose'],
['F653A6', 'Rosa brillante', 'Brilliant Rose'],
['F6A4C9', 'Illusione', 'Illusion'],
['F6F0E6', 'Merino', 'Merino'],
['F6F7F7', 'Haze Nero', 'Black Haze'],
['F6FFDC', 'Sole primaverile', 'Spring Sun'],
['F7468A', 'Viola rosso', 'Violet Red'],
['F77703', 'Fuoco cileno', 'Chilean Fire'],
['F77FBE', 'Rosa persiana', 'Persian Pink'],
['F7B668', 'tatuaggio', 'Rajah'],
['F7C8DA', 'Azalea', 'Azalea'],
['F7DBE6', 'Facciamo capolino', 'We Peep'],
['F7E89F', 'Giallo Napoli', 'Giallo Napoli'],
['F7F2E1', 'Quartiere spagnolo bianco', 'Quarter Spanish White'],
['F7F5FA', 'Sussurro', 'Whisper'],
['F7F7F7', 'Grigio 5%.', 'Grigio 5%'],
['F7FAF7', 'Deriva della neve', 'Snow Drift'],
['F8B853', 'Casablanca', 'Casablanca'],
['F8C3DF', 'Chantilly', 'Chantilly'],
['F8D9E9', 'Cherubino', 'Cherub'],
['F8DB9D', 'marzapane', 'Marzipan'],
['F8DD5C', 'Energia gialla', 'Energy Yellow'],
['F8E4BF', 'Dare', 'Givry'],
['F8F0E8', 'Biancheria bianca', 'White Linen'],
['F8F4FF', 'Magnolia', 'Magnolia'],
['F8F6F1', 'Legno Primaverile', 'Spring Wood'],
['F8F7DC', 'Crema di cocco', 'Coconut Cream'],
['F8F7FC', 'Lilla bianca', 'White Lilac'],
['F8F8F7', 'Tempesta Nel deserto', 'Desert Storm'],
['F8F8FF', 'Bianco Fantasma', 'Bianco Fantasma'],
['F8F99C', 'Texas', 'Texas'],
['F8FACD', 'Campo di mais', 'Corn Field'],
['F8FDD3', 'Mimosa', 'Mimosa'],
['F95A61', 'Garofano', 'Carnation'],
['F984E5', 'Magenta chiaro', 'Magenta chiaro'],
['F9BF58', 'Mango allo zafferano', 'Saffron Mango'],
['F9E0ED', 'Carosello Rosa', 'Carousel Pink'],
['F9E4BC', 'Crema di latte', 'Dairy Cream'],
['F9E663', 'Portica', 'Portica'],
['F9E6F4', 'Rosa minorenne', 'Underage Pink'],
['F9EAF3', 'Amore', 'Amour'],
['F9F8E4', 'Rum Swizzle', 'Rum Swizzle'],
['F9FF8B', 'bambola', 'Dolly'],
['F9FFF6', 'Canna da zucchero', 'Sugar Cane'],
['FA7814', 'Estasi', 'Ecstasy'],
['FA9D5A', 'Nascondi Tan', 'Tan Hide'],
['FAD3A2', 'Corvetta', 'Corvette'],
['FADADD', 'Rosa pallido', 'Rosa pallido'],
['FADFAD', 'Pesca-giallo', 'Giallo pesca'],
['FAE600', 'Turbo', 'Turbo'],
['FAEAB9', 'Astra', 'Astra'],
['FAEBD7', 'Bianco di Titanio', 'Bianco di Titanio'],
['FAECCC', 'Champagne', 'Champagne'],
['FAF0E6', 'Lino', 'Biancheria'],
['FAF3F0', 'Fantasia', 'Fantasy'],
['FAF7D6', 'Citrino Bianco', 'Citrine White'],
['FAFAFA', 'Alabastro', 'Alabaster'],
['FAFDE4', 'Suggerimento di giallo', 'Hint of Yellow'],
['FAFFA4', 'Milano', 'Milan'],
['FB607F', 'Rosa rosa', 'Brink Pink'],
['FB8989', 'Geraldina', 'Geraldine'],
['FBA0E3', 'Rosa di lavanda', 'Lavender Rose'],
['FBA129', 'Olivello spinoso', 'Sea Buckthorn'],
['FBAC13', 'Sole', 'Sun'],
['FBAED2', 'Rosa lavanda', 'Lavender Pink'],
['FBB2A3', 'Bocciolo di rosa', 'Rose Bud'],
['FBBEDA', 'Cupido', 'Cupid'],
['FBCCE7', 'Rosa classica', 'Classic Rose'],
['FBCEB1', 'Albicocca', 'Albicocca Peach'],
['FBE7B2', 'Mania banana', 'Banana Mania'],
['FBE870', 'Marigold Giallo', 'Marigold Yellow'],
['FBE96C', 'Festival', 'Festival'],
['FBEA8C', 'Mais dolce', 'Sweet Corn'],
['FBEC5D', 'Mais caramella', 'Candy Corn'],
['FBF9F9', 'Suggerimento di rosso', 'Hint of Red'],
['FBFFBA', 'Shalimar', 'Shalimar'],
['FC0FC0', 'Rosa scioccante', 'Rosa shocking', 'Rosa shocking'],
['FC6C85', 'Anguria', 'Anguria'],
['FC80A5', 'Tickle Me Rosa', 'Tickle Me Pink'],
['FC9C1D', "Papavero dell'albero", 'Tree Poppy'],
['FCC01E', 'Giallo lampo', 'Lightning Yellow'],
['FCD667', "Verga d'oro", 'Goldenrod'],
['FCD917', 'Lume di candela', 'Candlelight'],
['FCDA98', 'Cherokee', 'Cherokee'],
['FCF4D0', 'Double Pearl Lazy', 'Double Pearl Lusta'],
['FCF4DC', 'Perla della lussuria', 'Pearl Lusta'],
['FCF8F7', 'Vista Bianco', 'Vista White'],
['FCFBF3', 'Bianca', 'Bianca'],
['FCFEDA', 'Bagliore di luna', 'Moon Glow'],
['FCFFE7', 'Cina Ivory', 'China Ivory'],
['FCFFF9', 'Ceramica', 'Ceramic'],
['FD0E35', 'Torcia rossa', 'Torch Red'],
['FD5B78', 'Anguria selvaggia', 'Wild Watermelon'],
['FD7B33', 'crosta', 'Crusta'],
['FD7C07', 'Sorbo', 'Sorbus'],
['FD9FA2', 'Dolce rosa', 'Sweet Pink'],
['FDD5B1', 'Albicocca leggera', 'Light Apricot'],
['FDD7E4', 'Maiale rosa', 'Pig Pink'],
['FDE1DC', 'Cenerentola', 'Cinderella'],
['FDE295', 'Bagliore dorato', 'Golden Glow'],
['FDE910', 'Limone', 'Limone'],
['FDF5E6', 'Vecchio pizzo', 'Old Lace'],
['FDF6D3', 'Mezzo coloniale bianco', 'Half Colonial White'],
['FDF7AD', 'Mandriano', 'Drover'],
['FDFEB8', 'Primo pallido', 'Pale Prim'],
['FDFFD5', 'Cumulo', 'Cumulus'],
['FE28A2', 'Rosa persiana', 'Persian Rose'],
['FE4C40', 'Tramonto Arancione', 'Sunset Orange'],
['FE6F5E', 'Agrodolce', 'Bittersweet'],
['FE9D04', 'California', 'California'],
['FEA904', 'Mar Giallo', 'Yellow Sea'],
['FEBAAD', 'Melone', 'Melon'],
['FED33C', 'Sole luminoso', 'Bright Sun'],
['FED85D', 'Dente di leone', 'Dandelion'],
['FEDB8D', 'Salome', 'Salomie'],
['FEE5AC', 'Miele del Capo', 'Cape Honey'],
['FEEBF3', 'Resto', 'Remy'],
['FEEFCE', 'Oasi', 'Oasis'],
['FEF0EC', "damigella d'onore", 'Bridesmaid'],
['FEF2C7', "cera d'api", 'Beeswax'],
['FEF3D8', 'Candeggina bianca', 'Bleach White'],
['FEF4CC', 'guancia', 'Pipi'],
['FEF4DB', 'Mezzo spagnolo bianco', 'Half Spanish White'],
['FEF4F8', 'Sorseggiare Rosa', 'Wisp Pink'],
['FEF5F1', 'Rosa provinciale', 'Provincial Pink'],
['FEF7DE', 'Metà Bianco Olandese', 'Half Dutch White'],
['FEF8E2', 'Solitario', 'Solitaire'],
['FEF8FF', 'Puntatore bianco', 'White Pointer'],
['FEF9E3', 'Off Giallo', 'Off Yellow'],
['FEFCED', 'Arancione Bianco', 'Orange White'],
['FEFEE9', 'Bianco di Zinco', 'Bianco di Zinco'],
['FF0000', 'Rosso', 'Rosso'],
['FF007F', 'Rosa vivo', 'Rosa'],
['FF00CC', 'Pizzazz viola', 'Purple Pizzazz'],
['FF00FF', 'Magenta', 'Magenta / Fuchsia'],
['FF2400', 'Scarlatto', 'Scarlatto'],
['FF3399', 'Fragola selvatica', 'Wild Strawberry'],
['FF33CC', 'Ugello Rosa abbagliante', 'Razzle Dazzle Rose'],
['FF355E', 'Rosso radicale', 'Radical Red'],
['FF3F34', 'Arancia rossa', 'Red Orange'],
['FF4040', 'Rosso corallo', 'Coral Red'],
['FF4D00', 'Vermiglio', 'Vermiglio'],
['FF4F00', 'Orange internazionale', 'International Orange'],
['FF6037', 'Arancione oltraggioso', 'Outrageous Orange'],
['FF6088', 'Rosso rosa', 'Rosso rosa'],
['FF6347', 'Rosso pomodoro', 'Rosso pomodoro'],
['FF6600', 'Arancione fiammeggiante', 'Blaze Orange'],
['FF66FF', 'Fenicottero rosa', 'Pink Flamingo'],
['FF681F', 'arancia', 'Orange'],
['FF69B4', 'Rosa caldo', 'Hot Pink'],
['FF6B53', 'Cachi', 'Persimmon'],
['FF6FFF', 'Fardello Rosa', 'Blush Pink'],
['FF7034', 'Arancione bruciante', 'Burning Orange'],
['FF7518', 'Zucca', 'Pumpkin'],
['FF7D07', 'Flamenco', 'Flamenco'],
['FF7F00', 'Arancione a filo', 'Flush Orange'],
['FF7F50', 'Corallo', 'Corallo'],
['FF8C69', 'Salmone', 'salmone'],
['FF9000', 'pizazz', 'Pizazz'],
['FF910F', 'lato ovest', 'West Side'],
['FF91A4', 'Salmone rosa', 'Pink Salmon'],
['FF9933', 'Zafferano intenso', 'Carota al neon'],
['FF9966', 'Rosa arancio', 'Atomic Tangerine'],
['FF9980', 'Mandarino Vivido', 'Vivid Tangerine'],
['FF9E2C', 'Parasole', 'Sunshade'],
['FFA000', "Buccia d'arancia", 'Orange Peel'],
['FFA194', 'Monna Lisa', 'Mona Lisa'],
['FFA500', 'Arancione', 'Web Orange'],
['FFA6C9', 'Garofano rosa', 'Carnation Pink'],
['FFAB81', 'Rosa caldo', 'Hit Pink'],
['FFAE42', 'Arancione Giallo', 'Yellow Orange'],
['FFB0AC', 'Lillà di fiordaliso', 'Cornflower Lilac'],
['FFB1B3', 'Tramonto', 'Sundown'],
['FFB31F', 'Il mio peccato', 'My Sin'],
['FFB555', 'Rosa del Texas', 'Texas Rose'],
['FFB7D5', 'Zucchero filato', 'Cotton Candy'],
['FFB97B', 'Maccheroni e formaggio', 'Macaroni and Cheese'],
['FFBA00', 'Giallo selettivo', 'Selective Yellow'],
['FFBD5F', 'Koromiko', 'Koromiko'],
['FFBF00', 'Ambra', 'Ambra'],
['FFC0A8', 'Fiore di cera', 'Wax Flower'],
['FFC0CB', 'Rosa', 'Rosa'],
['FFC3C0', 'Il tuo rosa', 'Your Pink'],
['FFC901', 'Supernova', 'Supernova'],
['FFCBA4', 'Carne', 'Flesh'],
['FFCC00', 'Mandarino', 'Mandarino'],
['FFCC33', 'Sunglow', 'Sunglow'],
['FFCC5C', "Tainoi d'oro", 'Golden Tainoi'],
['FFCC99', 'Pesca-arancio', 'Arancia pesca'],
['FFCD8C', 'Chardonnay', 'Chardonnay'],
['FFD1DC', 'Rosa pastello', 'Rosa pastello'],
['FFD2B7', 'Romantico', 'Romantic'],
['FFD38C', 'Grandis', 'Grandis'],
['FFD700', 'Oro', 'Oro'],
['FFD800', 'Giallo scuolabus', 'Scuolabus Giallo'],
['FFD8D9', 'Cosmo', 'Cosmos'],
['FFDAB9', 'Pesca scuro', 'Pesca scuro'],
['FFDB58', 'Mostarda', 'Mustard'],
['FFDCD6', 'Grappa alla pesca', 'Peach Schnapps'],
['FFDDAF', 'Caramello', 'Caramel'],
['FFDDCD', 'Cift Bush', 'Tuft Bush'],
['FFDDCF', 'tutsi', 'Watusi'],
['FFDDF4', 'Pizzo rosa', 'Pink Lace'],
['FFDEAD', 'Bianco Navajo', 'Navajo bianco'],
['FFDEB3', 'Frangipani', 'Frangipani'],
['FFE1DF', 'Renetta', 'Pippin'],
['FFE1F2', 'Rosa pallida', 'Pale Rose'],
['FFE2C5', 'Negroni', 'Negroni'],
['FFE4C4', 'Biscotto', 'Biscotto'],
['FFE5A0', 'Creme brulee', 'Cream Brulee'],
['FFE5B4', 'Pesca', 'pesca'],
['FFE6C7', 'Tequila', 'Tequila'],
['FFE772', 'Kournikova', 'Kournikova'],
['FFEAC8', 'Spiaggia sabbiosa', 'Sandy Beach'],
['FFEAD4', 'curry', 'Karry'],
['FFEC13', 'Scopa', 'Broom'],
['FFEDBC', 'Coloniale bianco', 'Colonial White'],
['FFEED8', 'Derby', 'Derby'],
['FFEFA1', 'Mostra spettacolo', 'Vis Vis'],
['FFEFC1', 'Albume', 'Egg White'],
['FFEFD5', 'Papaia', 'Papaya Whip'],
['FFEFEC', 'Rosa Fiera', 'Fair Pink'],
['FFF0DB', 'Crema di pesca', 'Peach Cream'],
['FFF0F5', 'Lavanda rosata', 'La lavanda arrossisce'],
['FFF14F', 'ginestra', 'Gorse'],
['FFF1B5', 'Burro di latte', 'Buttermilk'],
['FFF1D8', 'Signora in rosa', 'Pink Lady'],
['FFF1EE', 'Non ti scordar di mé', 'Forget Me Not'],
['FFF1F9', 'tutu', 'Tutu'],
['FFF39D', 'Picasso', 'Picasso'],
['FFF3F1', 'cardo', 'Chardon'],
['FFF46E', 'Daisy a Parigi', 'Paris Daisy'],
['FFF4CE', 'Orzo bianco', 'Barley White'],
['FFF4DD', 'Uovo aspro', 'Egg Sour'],
['FFF4E0', 'Sazerac', 'Sazerac'],
['FFF4E8', 'Serenata', 'Serenade'],
['FFF4F3', 'Chablis', 'Chablis'],
['FFF5EE', 'Conchiglia', 'Seashell Peach'],
['FFF5F3', 'Sauvignon', 'Sauvignon'],
['FFF6D4', 'Punch al latte', 'Milk Punch'],
['FFF6DF', 'Giardino', 'Varden'],
['FFF6F5', 'Bianco Rosa', 'Rose White'],
['FFF8D1', 'Bianco Baja', 'Baja White'],
['FFF9E2', 'Gin Fizz', 'Gin Fizz'],
['FFF9E6', 'Alba presto', 'Early Dawn'],
['FFFACD', 'Limone crema', 'Chiffon al limone'],
['FFFAF0', 'Bianco Floreale', 'Bianco Floreale'],
['FFFAF4', 'Salute Sposa', 'Bridal Heath'],
['FFFBDC', 'Nebbia densa con pioggia', 'Scotch Mist'],
['FFFBF9', 'Pietra ollare', 'Soapstone'],
['FFFC99', 'Witch Hazel', 'Witch Haze'],
['FFFCEA', 'Burro Bianco', 'Buttery White'],
['FFFCEE', "Spice dell'isola", 'Island Spice'],
['FFFDD0', 'Crema', 'Crema'],
['FFFDE6', 'Heath cilena', 'Chilean Heath'],
['FFFDE8', 'Travertino', 'Travertine'],
['FFFDF3', 'Orchidea bianca', 'Orchid White'],
['FFFDF4', 'Quarter Pearl Lust', 'Quarter Pearl Lusta'],
['FFFEE1', 'Metà e metà', 'Half and Half'],
['FFFEEC', 'Albicocca Bianca', 'Apricot White'],
['FFFEEF', 'Bianco Antico', 'Bianco Antico'],
['FFFEF0', 'Torta di riso', 'Rice Cake'],
['FFFEF6', 'Nero bianco', 'Black White'],
['FFFEFD', 'Romanza', 'Romance'],
['FFFF00', 'Giallo', 'Giallo'],
['FFFF66', 'Giallo pastello', 'Laser Lemon'],
['FFFF99', 'Canarino pallido', 'Pale Canary'],
['FFFFB4', 'Portofino', 'Portafino'],
['FFFFF0', 'Avorio', 'Avorio'],
['FFFFFF', 'Bianco', 'Bianca', 'White']];

class Utils {
    constructor(env){
        this.env = env;
        ntc.names = names;
        ntc.init();
    }

    matrixInit(row, col){
        let matrix = [];
        for (var i=0; i<row; i++){
            let row = [];
            for (var j=0; j<col; j++){
                row.push(0);
            }
            matrix.push(row);
        }
        return matrix;
    }

    getNames(){
        return ntc.names;
    }

    getRandomInt(min, max) {
        return Math.floor(Math.random() * (max - min + 1)) + min;
    }

    tokenize(word){
        const oldWord = word.replace(/[^a-zA-Z0-9]/g, ' ').split(' ');
        const newWord = sw.removeStopwords(oldWord, sw.it);
        return sw.removeStopwords(newWord, ['','percento']);
    }

    rgb2hex(R,G,B){
        let str_r = R == 0 ? "00" : R.toString(16).toUpperCase();
        let str_g = G == 0 ? "00" : G.toString(16).toUpperCase();
        let str_b = B == 0 ? "00" : B.toString(16).toUpperCase();
        return str_r + str_g + str_b;
    }

    hex2rgb(hex){
        return {
            r: parseInt(hex.substring(1,3), 16),
            g: parseInt(hex.substring(3,5), 16),
            b: parseInt(hex.substring(5,7), 16)
        }
    }

    hex2png(hexs, size = 10){
        if (!Array.isArray(hexs)){
            hexs = [hexs];
        }

        let imageData = this.matrixInit(size, size);

        for (var i=0; i<imageData.length; i++){
            for (var j=0; j<imageData[i].length; j++){
                var index = (i*imageData.length + j)%hexs.length;
                var rgb = this.hex2rgb(hexs[index]);
                imageData[i][j] = Jimp.rgbaToInt(rgb.r, rgb.g, rgb.b, 255);
            }
        }

        let name = hexs.join("-").replace("#","");
        let image = new Jimp(size, size);
        async.waterfall([
            function(next){
                imageData.forEach((row, y) => {
                    row.forEach((color, x) => {
                    image.setPixelColor(color, x, y);
                    });
                });
                next(null);
            },
            function(next){
                image.resize(720, 480, Jimp.RESIZE_BEZIER);
                image.getBuffer(Jimp.MIME_JPEG, function (err, data){
                    if (err) next(err);
                    let params = {
                        Body: data,
                        Bucket: bucket_name,
                        Key: partition_name+'/'+ name +'-720x480.jpg',
                        StorageClass: 'ONEZONE_IA',
                        ACL: 'public-read'
                    };
                    console.log(params);
                    s3Client.putObject(params, function(err, data) {
                        if (err) console.log(err, err.stack);
                        else     console.log(data);
                        next(err);
                    });
                });
            },
            function(next){
                image.resize(1200, 800, Jimp.RESIZE_BEZIER);
                image.getBuffer(Jimp.MIME_JPEG, function (err, data){
                    if (err) next(err);
                    let params = {
                        Body: data,
                        Bucket: bucket_name,
                        Key: partition_name+'/'+ name +'-1200x800.jpg',
                        StorageClass: 'ONEZONE_IA',
                        ACL: 'public-read'
                    };
                    console.log(params);
                    s3Client.putObject(params, function(err, data) {
                        if (err) console.log(err, err.stack);
                        else     console.log(data);
                        next(err);
                    });
                });
            }
        ], function (err) {
                if (err) {
                    console.log("An error has occurred: " + err);
                    console.log("Enqueue");
                }
                else {
                    console.log('Successfully uploadede to Amazon S3!');
                }
        });

        return {
            smallImageUrl: 'https://s3-'+region+'.amazonaws.com/'+bucket_name+'/'+partition_name+'/'+ name +'-720x480.jpg',
            largeImageUrl: 'https://s3-'+region+'.amazonaws.com/'+bucket_name+'/'+partition_name+'/'+ name +'-1200x800.jpg'
        };

    }

    hex_mean(hexs, color_name){
        if ( !Array.isArray(hexs) )
            return hexs;
        //LOG Del nome di questo colore
        let size = hexs.length;
        let sum_r = 0;
        let sum_g = 0;
        let sum_b = 0;
        for ( var i = 0; i < size; i++ ){
            sum_r += parseInt(hexs[i].substring(0,2), 16);
            sum_g += parseInt(hexs[i].substring(2,4), 16);
            sum_b += parseInt(hexs[i].substring(4,6), 16);
        }
        return rgb2hex((sum_r/size),(sum_g/size), (sum_b/size));
    }

    name2hex(color_name, ColorMatrix){
        // aggiungere qua nomi strani "alias"
        // se alias rimuovi duplicati prima della media
        let source = this.tokenize(color_name);
        let source_join = source.join();

        let matrix = [];
        for ( var i = 0; i < source.length; i++ ) {
            matrix[i] = [];
        }

        for ( var i = 0; i < ColorMatrix.length; i++ ){
            let target = this.tokenize(ColorMatrix[i][0]);
            if ( source_join == target.join() ){
                for ( var t = 0; t < source.length; t++ ) {
                    matrix[t] = ColorMatrix[i][1];
                }
                break;
            }
            for ( var j = 0; j < Math.min(source.length, target.length); j++){
                let match = true;
                for ( var k = j; k >= 0; k-- ){
                    match = source[k] == target[k] && match;
                    if (!match) break;
                }
                if ( match ){
                    matrix[j].push(ColorMatrix[i][1]);
                }
            }
        }

        let hex_value;
        for ( var i = source.length-1; i >=0; i-- ) {
            if ( matrix[i].length > 0 ){
                hex_value = this.hex_mean(matrix[i], color_name);
                break;
            }
        }

        if ( color_name == undefined)
            console.log('undefined'); //LOG Del nome di questo colore
        return hex_value
    }

    hex(){
        let R = this.getRandomInt(0, 255);
        let G = this.getRandomInt(0, 255);
        let B = this.getRandomInt(0, 255);
        return this.rgb2hex(R,G,B);
    }

    name(hex){
        return ntc.name(hex);
    }

    harmonize(color_hex, type){
        return harmonizer.harmonize(color_hex, type);
    }

    harmonizeAll(color_hex){
        return harmonizer.harmonizeAll(color_hex);
    }


    async saveDiscardedArticles(articles){
        return await this.bucket.putArticles(articles, 'discarded');
    }

    async saveArticlesWithoutImages(articles) {
        return await this.bucket.putArticles(articles, 'noImages');
    }
}


module.exports = Utils
